(()=>{
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let data=null;
const e=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function fmtPrize(x){return x.type==='DISCOUNT'?`${x.value}%`:x.type==='CREDIT'?`${x.value}$ Credit`:x.label}
async function loadRewards(){try{data=await api('/api/admin/rewards');$('#rMemberCount').textContent=Number(data.memberCount).toLocaleString();$('#rTarget').textContent=Number(data.config.target_members).toLocaleString();$('#rRemaining').textContent=Math.max(0,data.config.target_members-data.memberCount).toLocaleString();$('#rState').textContent=data.memberCount>=data.config.target_members?'ACTIVE':'WAITING';$('#rewardTargetInput').value=data.config.target_members;$('#rewardHourInput').value=data.config.friday_hour;$('#rewardExpiryInput').value=data.config.credit_expiry_days;$('#rewardEnabledInput').checked=!!data.config.enabled;$('#rewardQrImage').src='/api/admin/rewards/qr.svg?'+Date.now();
$('#adminRewardPrizes').innerHTML=data.prizes.map(p=>`<div class="row"><div><b>${e(p.label)}</b><div class="muted">${p.is_grand?'👑 SUPER • ':''}${e(p.type)} • min ${Number(p.min_purchase_usd).toLocaleString()}$</div></div><span>${e(fmtPrize(p))}</span><label>Weight <input data-rweight="${p.id}" type="number" min="1" value="${p.weight}" style="width:70px"></label><label><input data-ractive="${p.id}" type="checkbox" ${p.active?'checked':''}> Active</label></div>`).join('');
$('#adminRewardMembers').innerHTML=data.members.slice(0,200).map(m=>`<div class="row"><div><b>${e(m.customer_name)}</b><div class="muted">${e(m.phone)} · ${e(m.email||'')}</div></div><span>${m.wins_count} win</span><span>${e(m.joined_at)}</span></div>`).join('')||'<p class="muted">هێشتا ئەندام نییە</p>';
$('#adminRewardDraws').innerHTML=data.draws.map(d=>`<div class="row"><div><b>${d.is_grand?'👑':'🎁'} ${e(d.customer_name)}</b><div class="muted">${e(d.phone)} · ${e(d.drawn_at)} · ${d.participant_count} participants</div></div><span>${e(d.prize_label)}</span><code>${e(d.redeem_code)}</code>${d.redeem_status==='REDEEMED'?'<b>REDEEMED</b>':`<button data-redeem="${d.id}">Redeem</button>`}</div>`).join('')||'<p class="muted">هێشتا ڕاکێشان نەکراوە</p>';
$$('[data-rweight]').forEach(x=>x.onchange=()=>updatePrize(x.dataset.rweight,{weight:Number(x.value)}));$$('[data-ractive]').forEach(x=>x.onchange=()=>updatePrize(x.dataset.ractive,{active:x.checked}));$$('[data-redeem]').forEach(x=>x.onclick=()=>redeem(x.dataset.redeem));
}catch(err){note(err.message,false)}}
async function updatePrize(id,body){try{await api('/api/admin/rewards/prizes/'+id,{method:'PATCH',body:JSON.stringify(body)});note('خەڵات نوێکرایەوە');loadRewards()}catch(err){note(err.message,false)}}
async function redeem(id){if(!confirm('ئەم خەڵاتە وەک بەکارهاتوو تۆمار بکرێت؟'))return;try{await api('/api/admin/rewards/draws/'+id+'/redeem',{method:'POST',body:'{}'});note('خەڵات Redeem کرا');loadRewards()}catch(err){note(err.message,false)}}
async function draw(grand){if(!confirm(grand?'Super Prize ئێستا ڕاکێشان بکرێت؟':'Friday Gift ئێستا ڕاکێشان بکرێت؟'))return;try{const d=await api('/api/admin/rewards/draw',{method:'POST',body:JSON.stringify({grand})});alert(`براوە: ${d.winner.customer_name}\nخەڵات: ${d.prize.label}\nCode: ${d.redeemCode}`);loadRewards()}catch(err){note(err.message,false)}}
function bind(){const btn=$('[data-tab="rewardsTab"]');if(btn)btn.addEventListener('click',loadRewards);$('#refreshRewards')?.addEventListener('click',loadRewards);$('#printRewardQr')?.addEventListener('click',()=>{const src=$('#rewardQrImage')?.src;if(!src)return;const w=window.open('','_blank','width=700,height=850');w.document.write(`<html><head><title>DEVA Rewards QR</title><style>body{font-family:Arial;text-align:center;padding:40px}img{width:420px;max-width:90%}h1{margin:10px}p{font-size:18px}</style></head><body><h1>DEVA Rewards Club</h1><p>QR سکان بکە، خۆت تۆمار بکە و بەژداری خەڵاتەکانی DEVA بە</p><img src="${src}"><script>setTimeout(()=>print(),600)<\/script></body></html>`);w.document.close()});$('#drawFridayNow')?.addEventListener('click',()=>draw(false));$('#drawGrandNow')?.addEventListener('click',()=>draw(true));$('#rewardSettingsForm')?.addEventListener('submit',async ev=>{ev.preventDefault();try{await api('/api/admin/rewards/settings',{method:'PATCH',body:JSON.stringify({target_members:Number($('#rewardTargetInput').value),friday_hour:Number($('#rewardHourInput').value),credit_expiry_days:Number($('#rewardExpiryInput').value),enabled:$('#rewardEnabledInput').checked})});note('Rewards settings هەڵگیرا');loadRewards()}catch(err){note(err.message,false)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();

// V9 — live audience stats for DEVA Rewards
(()=>{
 function nextFri(){const now=new Date();for(let i=0;i<8;i++){const d=new Date(now);d.setDate(now.getDate()+i);d.setHours(21,0,0,0);if(d.getDay()===5&&d>now)return d}const d=new Date(now);d.setDate(now.getDate()+7);d.setHours(21,0,0,0);return d}
 function clock(){const el=document.querySelector('#rLiveCountdown');if(!el)return;let t=Math.max(0,nextFri()-new Date()),s=Math.floor(t/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),x=s%60;el.textContent=`${d}d ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
 async function live(){try{const d=await api('/api/admin/rewards/live');document.querySelector('#rOnlineNow').textContent=Number(d.onlineNow||0).toLocaleString();document.querySelector('#rRewardsNow').textContent=Number(d.inRewardsNow||0).toLocaleString();document.querySelector('#rWaitingNow').textContent=Number(d.waitingForDraw||0).toLocaleString()}catch{}}
 setInterval(clock,1000);setInterval(live,10000);clock();live();
})();
