(()=>{
const qs=s=>document.querySelector(s); let publicData=null,scanStream=null,pollTimer=null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const phone=()=>{try{return JSON.parse(localStorage.getItem('deva-customer')||'null')?.phone||''}catch{return''}};
const profile=()=>{try{return JSON.parse(localStorage.getItem('deva-customer')||'null')}catch{return null}};
async function jfetch(url,opt){const r=await fetch(url,{headers:{'content-type':'application/json'},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function prizeText(p){if(p.type==='DISCOUNT')return `${p.value}% داشکاندن`;if(p.type==='CREDIT')return `${p.value}$ DEVA Credit`;return p.label}
function nextFriday9(){const now=new Date();for(let i=0;i<8;i++){const d=new Date(now);d.setDate(now.getDate()+i);d.setHours(21,0,0,0);if(d.getDay()===5&&d>now)return d}const d=new Date(now);d.setDate(now.getDate()+7);d.setHours(21,0,0,0);return d}
function countdown(){const el=qs('#rewardCountdown');if(!el)return;const ms=nextFriday9()-new Date();const days=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);el.textContent=`${days} ڕۆژ، ${h} کاتژمێر، ${m} خولەک تا ڕاکێشان`}
function renderOfflineFallback(){const prizes=[['10% داشکاندن'],['15% داشکاندن'],['20% داشکاندن'],['25% داشکاندن'],['50$ DEVA Credit'],['100$ DEVA Credit'],['150$ DEVA Credit'],['200$ DEVA Credit'],['300$ DEVA Credit'],['👑 TV Unit • Super Prize'],['👑 3-Piece Coffee Table Set • Super Prize']];if(qs('#rewardMemberCount'))qs('#rewardMemberCount').textContent='0 / 1,000';if(qs('#rewardProgress'))qs('#rewardProgress').style.width='0%';if(qs('#rewardStartState'))qs('#rewardStartState').textContent='Preview Mode • پاش پەیوەستکردنی Server ژمارەی ڕاستەقینە نیشان دەدرێت';if(qs('#rewardPrizes'))qs('#rewardPrizes').innerHTML=prizes.map((p,i)=>`<div class="reward-prize ${i>8?'grand':''}">${p[0]}</div>`).join('');if(qs('#rewardWinners'))qs('#rewardWinners').innerHTML='<p>هێشتا براوەیەک تۆمار نەکراوە.</p>';if(qs('#rewardMyStatus'))qs('#rewardMyStatus').innerHTML='📍 بۆ چالاککردنی ئەندامێتی، لە وەشانی ئۆنلاین QR ـی پێشانگا سکان بکە.'}
async function loadPublic(){try{publicData=await jfetch('/api/rewards/public');const pct=Math.min(100,Math.round(publicData.members/publicData.target*100));qs('#rewardMemberCount').textContent=`${Number(publicData.members).toLocaleString()} / ${Number(publicData.target).toLocaleString()}`;qs('#rewardProgress').style.width=pct+'%';qs('#rewardStartState').textContent=publicData.started?'✅ خەڵاتە هەفتانەکان چالاکن':'تەنها '+Math.max(0,publicData.target-publicData.members).toLocaleString()+' ئەندام ماوە بۆ دەستپێکردن';qs('#rewardPrizes').innerHTML=publicData.prizes.map(p=>`<div class="reward-prize ${p.is_grand?'grand':''}">${p.is_grand?'👑 ':''}${esc(prizeText(p))}${p.is_grand?'<small><br>Super Prize • هەر ٣ مانگ</small>':''}</div>`).join('');qs('#rewardWinners').innerHTML=publicData.recent.length?publicData.recent.map(x=>`<div class="reward-winner"><span>${x.is_grand?'👑':'🎁'} ${esc(x.customer_name)} <small>${esc(x.phone)}</small></span><b>${esc(x.label)}</b></div>`).join(''):'<p>هێشتا براوەیەک تۆمار نەکراوە.</p>';await loadMember()}catch(e){renderOfflineFallback()} }
async function loadMember(){const p=phone();const box=qs('#rewardMyStatus');if(!p){box.innerHTML='بۆ چالاککردنی DEVA Rewards سەرەتا هەژماری کریار دروست بکە.';return}try{const d=await jfetch('/api/rewards/member?phone='+encodeURIComponent(p));if(!d.member){box.innerHTML='❌ هێشتا ئەندامی DEVA Rewards نیت. یەک جار QR ـی پێشانگا سکان بکە.';return}box.innerHTML=`✅ ئەندامێتی تۆ چالاکە • ${Number(d.member.wins_count).toLocaleString()} خەڵات بردووەتەوە`+(d.wins[0]?`<br><b>دوا خەڵات: ${esc(d.wins[0].label)} — ${esc(d.wins[0].redeem_status)}</b>`:'');const unseen=d.wins.find(w=>localStorage.getItem('deva-reward-seen-'+w.id)!=='1');if(unseen){showGift(unseen);localStorage.setItem('deva-reward-seen-'+unseen.id,'1');if('Notification'in window&&Notification.permission==='granted')new Notification('DEVA Friday Gift',{body:`پیرۆزە! ${unseen.label} ـت بردووەتەوە.`})}}catch(e){box.textContent=e.message}}
function openJoin(token=''){const p=profile();qs('#rewardName').value=p?.name||'';qs('#rewardPhone').value=p?.phone||'';qs('#rewardEmail').value=p?.email||'';qs('#rewardToken').value=token;qs('#rewardJoinModal').classList.add('open')}
function closeModal(id){qs(id)?.classList.remove('open');if(id==='#rewardJoinModal')stopCamera()}
async function activateWithProfile(p,token){if(!p?.name||!p?.phone||!token)return false;await jfetch('/api/rewards/activate',{method:'POST',body:JSON.stringify({customer_name:String(p.name).trim(),phone:String(p.phone).trim(),email:String(p.email||'').trim(),token:String(token).trim(),consent:true})});localStorage.setItem('deva-reward-activated','1');localStorage.removeItem('deva-reward-pending-token');return true}
async function activate(){const body={customer_name:qs('#rewardName').value.trim(),phone:qs('#rewardPhone').value.trim(),email:qs('#rewardEmail').value.trim(),token:qs('#rewardToken').value.trim(),consent:qs('#rewardConsent').checked};try{await jfetch('/api/rewards/activate',{method:'POST',body:JSON.stringify(body)});localStorage.setItem('deva-reward-activated','1');localStorage.removeItem('deva-reward-pending-token');qs('#rewardJoinMsg').textContent='✅ ئەندامێتی DEVA Rewards چالاک کرا.';setTimeout(()=>{closeModal('#rewardJoinModal');loadPublic();document.querySelector('#devaRewards')?.scrollIntoView({behavior:'smooth',block:'start'})},700)}catch(e){qs('#rewardJoinMsg').textContent='❌ '+e.message}}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){qs('#rewardJoinMsg').textContent='کامێرا لەم وێبگەڕەدا پشتگیری ناکرێت؛ QR بە Camera ـی مۆبایل سکان بکە.';return}if(!('BarcodeDetector'in window)){qs('#rewardJoinMsg').textContent='Scan ـی ناوخۆیی لەم مۆبایلەدا پشتگیری ناکرێت؛ QR بە Camera ـی مۆبایل سکان بکە.';return}try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=qs('#rewardVideo');v.srcObject=scanStream;await v.play();const det=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!scanStream)return;try{const codes=await det.detect(v);if(codes[0]){const raw=codes[0].rawValue||'';const token=parseToken(raw);if(token){qs('#rewardToken').value=token;qs('#rewardJoinMsg').textContent='✅ QR سکان کرا';stopCamera();return}}}catch{}requestAnimationFrame(loop)};loop()}catch(e){qs('#rewardJoinMsg').textContent='دەستگەیشتن بە کامێرا ڕێگەپێنەدرا'}}
function parseToken(raw){try{const u=new URL(raw);return u.searchParams.get('deva_reward')||raw}catch{return raw}}
function stopCamera(){if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}const v=qs('#rewardVideo');if(v)v.srcObject=null}
function showGift(w){qs('#giftRevealTitle').textContent=w.label;qs('#giftRevealCode').textContent='کۆدی خەڵات: '+w.redeem_code;qs('#mysteryGiftBox').classList.remove('opened');qs('#rewardGiftModal').classList.add('open')}
function init(){
 qs('#rewardJoinBtn')?.addEventListener('click',()=>openJoin(''));const openScanner=()=>{openJoin('');setTimeout(startCamera,120)};qs('#rewardScanBtn')?.addEventListener('click',openScanner);qs('#rewardActivateBtn')?.addEventListener('click',activate);qs('#rewardNotifyBtn')?.addEventListener('click',async()=>{if('Notification'in window)await Notification.requestPermission()});document.querySelectorAll('[data-reward-close]').forEach(b=>b.onclick=()=>closeModal('#'+b.dataset.rewardClose));qs('#mysteryGiftBox')?.addEventListener('click',e=>e.currentTarget.classList.add('opened'));
 const token=new URLSearchParams(location.search).get('deva_reward');if(token){localStorage.setItem('deva-reward-pending-token',token);history.replaceState({},'',location.pathname+location.hash);setTimeout(async()=>{const p=profile();if(p?.name&&p?.phone){try{await activateWithProfile(p,token);await loadPublic();document.querySelector('#devaRewards')?.scrollIntoView({behavior:'smooth',block:'start'});const box=qs('#rewardMyStatus');if(box)box.innerHTML='✅ سکانکردن سەرکەوتوو بوو — تۆ ئێستا ئەندامی DEVA Rewards یت.'}catch(e){openJoin(token);qs('#rewardJoinMsg').textContent='❌ '+e.message}}else{window.__DEVA_REWARD_PENDING__=token;document.querySelector('#accountBtn')?.click();setTimeout(()=>{const n=document.querySelector('#customerName');if(n)n.focus()},250)}},500)}
 window.DEVA_REWARDS={handleProfileSaved:async(p)=>{const t=localStorage.getItem('deva-reward-pending-token')||window.__DEVA_REWARD_PENDING__;if(!t)return false;try{await activateWithProfile(p,t);window.__DEVA_REWARD_PENDING__='';await loadPublic();document.querySelector('#accountModal [data-close=accountModal]')?.click();document.querySelector('#devaRewards')?.scrollIntoView({behavior:'smooth',block:'start'});const box=qs('#rewardMyStatus');if(box)box.innerHTML='✅ خۆت تۆمار کرد و ئەندامێتی DEVA Rewards ـت خۆکارانە چالاک بوو.';return true}catch(e){openJoin(t);qs('#rewardJoinMsg').textContent='❌ '+e.message;return false}}};
 loadPublic();countdown();setInterval(countdown,60000);pollTimer=setInterval(loadMember,60000)
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();

// V9 — Live Draw Room, exact countdown and live presence
(()=>{
 const sid=localStorage.getItem('deva-live-session')||((crypto.randomUUID?.()||('s'+Math.random().toString(36).slice(2)+Date.now())));localStorage.setItem('deva-live-session',sid);
 let warned15=false;
 function target(){return nextFriday9()}
 function tickExact(){const el=qs('#rewardCountdown'),state=qs('#rewardDrawState');if(!el)return;let ms=target()-new Date();if(ms<0)ms=0;const total=Math.floor(ms/1000),d=Math.floor(total/86400),h=Math.floor(total%86400/3600),m=Math.floor(total%3600/60),sec=total%60;el.textContent=`${d} ڕۆژ • ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;if(state)state.textContent=ms<=1000?'🔴 ڕاکێشان دەستی پێکرد':'⏳ چاوەڕێی ڕاکێشانی داهاتوو';if(ms>0&&ms<=15*60*1000&&!warned15){warned15=true;if('Notification'in window&&Notification.permission==='granted')new Notification('DEVA Friday Gift',{body:'15 خولەک ماوە بۆ ڕاکێشانی DEVA — ئێستا بچۆ ناو بەشی دیارییەکان.'})}}
 function inRewards(){const r=document.querySelector('#devaRewards');if(!r)return false;const b=r.getBoundingClientRect();return b.top<innerHeight&&b.bottom>0}
 async function heartbeat(){if(document.hidden)return;const area=inRewards()?'REWARDS':'APP';try{await fetch('/api/rewards/presence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:sid,area,waiting:area==='REWARDS'})});const d=await fetch('/api/rewards/live',{cache:'no-store'}).then(r=>r.json());const el=qs('#rewardWaitingNow');if(el)el.textContent=Number(d.waitingForDraw||0).toLocaleString()}catch{}}
 setInterval(tickExact,1000);setInterval(heartbeat,15000);addEventListener('scroll',()=>heartbeat(),{passive:true});document.addEventListener('visibilitychange',heartbeat);tickExact();heartbeat();
})();
