(()=>{
const qs=s=>document.querySelector(s); let publicData=null,scanStream=null,pollTimer=null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const phone=()=>{try{return JSON.parse(localStorage.getItem('deva-customer')||'null')?.phone||''}catch{return''}};
const profile=()=>{try{return JSON.parse(localStorage.getItem('deva-customer')||'null')}catch{return null}};
async function jfetch(url,opt){const r=await fetch(url,{headers:{'content-type':'application/json'},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function prizeText(p){if(p.type==='DISCOUNT')return `${p.value}% داشکاندن`;if(p.type==='CREDIT')return `${p.value}$ DEVA Credit`;return p.label}
function nextFriday9(){const now=new Date();for(let i=0;i<8;i++){const d=new Date(now);d.setDate(now.getDate()+i);d.setHours(21,0,0,0);if(d.getDay()===5&&d>now)return d}const d=new Date(now);d.setDate(now.getDate()+7);d.setHours(21,0,0,0);return d}
function countdown(){const el=qs('#rewardCountdown');if(!el)return;const ms=nextFriday9()-new Date();const days=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);el.textContent=`${days} ڕۆژ، ${h} کاتژمێر، ${m} خولەک تا ڕاکێشان`}
function renderOfflineFallback(){const prizes=[['10% داشکاندن'],['15% داشکاندن'],['20% داشکاندن'],['25% داشکاندن'],['50$ DEVA Credit'],['100$ DEVA Credit'],['150$ DEVA Credit'],['200$ DEVA Credit'],['300$ DEVA Credit'],['👑 TV Unit • Super Prize'],['👑 3-Piece Coffee Table Set • Super Prize']];if(qs('#rewardMemberCount'))qs('#rewardMemberCount').textContent='0 / 1,000';if(qs('#rewardProgress'))qs('#rewardProgress').style.width='0%';if(qs('#rewardStartState'))qs('#rewardStartState').textContent='Preview Mode • پاش پەیوەستکردنی Server ژمارەی ڕاستەقینە نیشان دەدرێت';if(qs('#rewardPrizes'))qs('#rewardPrizes').innerHTML=prizes.map((p,i)=>`<div class="reward-prize ${i>8?'grand':''}">${p[0]}</div>`).join('');if(qs('#rewardWinners'))qs('#rewardWinners').innerHTML='<p>هێشتا براوەیەک تۆمار نەکراوە.</p>';if(qs('#rewardMyStatus'))qs('#rewardMyStatus').innerHTML='📍 بۆ چالاککردنی ئەندامێتی، لە وەشانی ئۆنلاین QR ـی پێشانگا سکان بکە.'}
async function loadPublic(){try{publicData=await jfetch('/api/rewards/public');const pct=Math.min(100,Math.round(publicData.members/publicData.target*100));qs('#rewardMemberCount').textContent=`${Number(publicData.members).toLocaleString()} / ${Number(publicData.target).toLocaleString()}`;qs('#rewardProgress').style.width=pct+'%';qs('#rewardStartState').textContent=publicData.started?'✅ خەڵاتە هەفتانەکان چالاکن':'تەنها '+Math.max(0,publicData.target-publicData.members).toLocaleString()+' ئەندام ماوە بۆ دەستپێکردن';qs('#rewardPrizes').innerHTML=publicData.prizes.map(p=>`<div class="reward-prize ${p.is_grand?'grand':''}">${p.is_grand?'👑 ':''}${esc(prizeText(p))}${p.is_grand?'<small><br>Super Prize • هەر ٣ مانگ</small>':''}</div>`).join('');qs('#rewardWinners').innerHTML=publicData.recent.length?publicData.recent.map(x=>`<div class="reward-winner"><span>${x.is_grand?'👑':'🎁'} ${esc(x.customer_name)} <small>${esc(x.phone)}</small></span><b>${esc(x.label)}</b></div>`).join(''):'<p>هێشتا براوەیەک تۆمار نەکراوە.</p>';await loadMember()}catch(e){renderOfflineFallback()} }
async function loadMember(){const p=phone();const box=qs('#rewardMyStatus');if(!p){box.innerHTML='بۆ چالاککردنی DEVA Rewards سەرەتا هەژماری کریار دروست بکە.';return}try{const d=await jfetch('/api/rewards/member?phone='+encodeURIComponent(p));if(!d.member){box.innerHTML='❌ هێشتا ئەندامی DEVA Rewards نیت. یەک جار QR ـی پێشانگا سکان بکە.';return}box.innerHTML=`✅ ئەندامێتی تۆ چالاکە • ${Number(d.member.wins_count).toLocaleString()} خەڵات بردووەتەوە`+(d.wins[0]?`<br><b>دوا خەڵات: ${esc(d.wins[0].label)} — ${esc(d.wins[0].redeem_status)}</b>`:'');const unseen=d.wins.find(w=>localStorage.getItem('deva-reward-seen-'+w.id)!=='1');if(unseen){showGift(unseen);localStorage.setItem('deva-reward-seen-'+unseen.id,'1');if('Notification'in window&&Notification.permission==='granted')new Notification('DEVA Friday Gift',{body:`پیرۆزە! ${unseen.label} ـت بردووەتەوە.`})}}catch(e){box.textContent=e.message}}
function openJoin(token=''){const p=profile();qs('#rewardName').value=p?.name||'';qs('#rewardPhone').value=p?.phone||'';qs('#rewardEmail').value=p?.email||'';qs('#rewardToken').value=token;qs('#rewardJoinModal').classList.add('open')}
function closeModal(id){qs(id)?.classList.remove('open');if(id==='#rewardJoinModal')stopCamera()}
async function activateWithProfile(p,token){if(!p?.name||!p?.phone||!token)return false;await jfetch('/api/rewards/activate',{method:'POST',body:JSON.stringify({customer_name:String(p.name).trim(),phone:String(p.phone).trim(),email:String(p.email||'').trim(),token:String(token).trim(),consent:true})});localStorage.setItem('deva-reward-activated','1');localStorage.removeItem('deva-reward-pending-token');return true}
async function activate(){const body={customer_name:qs('#rewardName').value.trim(),phone:qs('#rewardPhone').value.trim(),email:qs('#rewardEmail').value.trim(),token:qs('#rewardToken').value.trim(),consent:qs('#rewardConsent').checked};try{await jfetch('/api/rewards/activate',{method:'POST',body:JSON.stringify(body)});localStorage.setItem('deva-reward-activated','1');localStorage.removeItem('deva-reward-pending-token');qs('#rewardJoinMsg').textContent='✅ ئەندامێتی DEVA Rewards چالاک کرا.';setTimeout(()=>{closeModal('#rewardJoinModal');loadPublic();document.querySelector('#devaRewards')?.scrollIntoView({behavior:'smooth',block:'start'})},700)}catch(e){qs('#rewardJoinMsg').textContent='❌ '+e.message}}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){qs('#rewardJoinMsg').textContent='کامێرا لەم وێبگەڕەدا پشتگیری ناکرێت؛ QR بە Camera ـی مۆبایل سکان بکە.';return}if(!('BarcodeDetector'in window)){qs('#rewardJoinMsg').textContent='Scan ـی ناوخۆیی لەم مۆبایلەدا پشتگیری ناکرێت؛ QR بە Camera ـی مۆبایل سکان بکە.';return}try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=qs('#rewardVideo');v.srcObject=scanStream;await v.play();const det=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!scanStream)return;try{const codes=await det.detect(v);if(codes[0]){const raw=codes[0].rawValue||'';const token=parseToken(raw);if(token){qs('#rewardToken').value=token;qs('#rewardJoinMsg').textContent='✅ QR سکان کرا';stopCamera();return}}}catch{}requestAnimationFrame(loop)};loop()}catch(e){qs('#rewardJoinMsg').textContent='دەستگەیشتن بە کامێرا ڕێگەپێنەدرا'}}
function parseToken(raw){try{const u=new URL(raw);return u.searchParams.get('deva_reward')||raw}catch{return raw}}
function stopCamera(){if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}const v=qs('#rewardVideo');if(v)v.srcObject=null}
function showGift(w){qs('#giftRevealTitle').textContent=w.label;qs('#giftRevealCode').textContent='کۆدی خەڵات: '+w.redeem_code;qs('#mysteryGiftBox').classList.remove('opened');qs('#rewardGiftModal').classList.add('open')}
function init(){
 qs('#rewardJoinBtn')?.addEventListener('click',()=>openJoin(''));const openScanner=()=>{openJoin('');setTimeout(startCamera,120)};qs('#rewardScanBtn')?.addEventListener('click',openScanner);qs('#rewardActivateBtn')?.addEventListener('click',activate);qs('#rewardNotifyBtn')?.addEventListener('click',async()=>{if('Notification'in window)await Notification.requestPermission()});document.querySelectorAll('[data-reward-close]').forEach(b=>b.onclick=()=>closeModal('#'+b.dataset.rewardClose));qs('#mysteryGiftBox')?.addEventListener('click',e=>e.currentTarget.classList.add('opened'));
 const token=new URLSearchParams(location.search).get('deva_reward');if(token){localStorage.setItem('deva-reward-pending-token',token);history.replaceState({},'',location.pathname+location.hash);setTimeout(async()=>{const p=profile();if(p?.name&&p?.phone){try{await activateWithProfile(p,token);await loadPublic();document.querySelector('#devaRewards')?.scrollIntoView({behavior:'smooth',block:'start'});const box=qs('#rewardMyStatus');if(box)box.innerHTML='✅ سکانکردن سەرکەوتوو بوو — تۆ ئێستا ئەندامی DEVA Rewards یت.'}catch(e){openJoin(token);qs('#rewardJoinMsg').textContent='❌ '+e.message}}else{window.__DEVA_REWARD_PENDING__=token;document.querySelector('#accountBtn')?.click();setTimeout(()=>{const n=document.querySelector('#customerName');if(n)n.focus()},250)}},500)}
 window.DEVA_REWARDS={handleProfileSaved:async(p)=>{const t=localStorage.getItem('deva-reward-pending-token')||window.__DEVA_REWARD_PENDING__;if(!t)return false;try{await activateWithProfile(p,t);window.__DEVA_REWARD_PENDING__='';await loadPublic();document.querySelector('#accountModal [data-close=accountModal]')?.click();document.querySelector('#devaRewards')?.scrollIntoView({behavior:'smooth',block:'start'});const box=qs('#rewardMyStatus');if(box)box.innerHTML='✅ خۆت تۆمار کرد و ئەندامێتی DEVA Rewards ـت خۆکارانە چالاک بوو.';return true}catch(e){openJoin(t);qs('#rewardJoinMsg').textContent='❌ '+e.message;return false}}};
 loadPublic();countdown();setInterval(countdown,60000);pollTimer=setInterval(loadMember,60000)
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();

// V9 — Live Draw Room, exact countdown and live presence
(()=>{
 const sid=localStorage.getItem('deva-live-session')||((crypto.randomUUID?.()||('s'+Math.random().toString(36).slice(2)+Date.now())));localStorage.setItem('deva-live-session',sid);
 let warned15=false;
 function target(){return nextFriday9()}
 function tickExact(){const el=qs('#rewardCountdown'),state=qs('#rewardDrawState');if(!el)return;let ms=target()-new Date();if(ms<0)ms=0;const total=Math.floor(ms/1000),d=Math.floor(total/86400),h=Math.floor(total%86400/3600),m=Math.floor(total%3600/60),sec=total%60;el.textContent=`${d} ڕۆژ • ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;if(state)state.textContent=ms<=1000?'🔴 ڕاکێشان دەستی پێکرد':'⏳ چاوەڕێی ڕاکێشانی داهاتوو';if(ms>0&&ms<=15*60*1000&&!warned15){warned15=true;if('Notification'in window&&Notification.permission==='granted')new Notification('DEVA Friday Gift',{body:'15 خولەک ماوە بۆ ڕاکێشانی DEVA — ئێستا بچۆ ناو بەشی دیارییەکان.'})}}
 function inRewards(){const r=document.querySelector('#devaRewards');if(!r)return false;const b=r.getBoundingClientRect();return b.top<innerHeight&&b.bottom>0}
 async function heartbeat(){if(document.hidden)return;const area=inRewards()?'REWARDS':'APP';try{await fetch('/api/rewards/presence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:sid,area,waiting:area==='REWARDS'})});const d=await fetch('/api/rewards/live',{cache:'no-store'}).then(r=>r.json());const el=qs('#rewardWaitingNow');if(el)el.textContent=Number(d.waitingForDraw||0).toLocaleString()}catch{}}
 setInterval(tickExact,1000);setInterval(heartbeat,15000);addEventListener('scroll',()=>heartbeat(),{passive:true});document.addEventListener('visibilitychange',heartbeat);tickExact();heartbeat();
})();


// DEVA Rewards — complete 4-language UI localization
(()=>{
const R={
ku:{nav:'دیارییەکانی DEVA',launchTitle:'دیارییەکانی DEVA',launchText:'یەک جار لە پێشانگا QR سکان بکە و بەردەوام لە ڕاکێشانی هەفتانە بەژدار بە. دوای گەیشتن بە 1,000 ئەندام، هەموو هەینی کاتژمێر 9ی شەو خەڵات دەدرێت.',view:'بینینی دیارییەکان',mainTitle:'خەڵاتی هەفتانەی DEVA',mainText:'ئەپلیکەیشنەکە دابەزێنە، تەنها یەک جار لە پێشانگا QR سکان بکە و ببە بە ئەندامی هەمیشەیی. دوای گەیشتن بە 1,000 ئەندام، هەموو هەینی کاتژمێر 9ی شەو ڕاکێشان دەکرێت.',drawLabel:'کاتی ڕاکێشان',drawText:'هەموو هەینی • 9:00 شەو',prizes:'🎁 خەڵاتەکان',scan:'QR سکان بکە',join:'ئەندامێتی خۆم بپشکنە',notify:'Notification چالاک بکە',credit:'DEVA Credit پارەی نەقد نییە و تەنها بۆ کڕینی داهاتوو بەکاردێت. مەرج و کەمترین بڕی کڕین لەلایەن DEVA دیاری دەکرێت.',winners:'🏆 لیستی براوەکان',float:'دیارییەکان',activateTitle:'چالاککردنی DEVA Rewards',activateHelp:'لە پێشانگا QR سکان بکە. تەنها یەک جار پێویستە.',name:'ناوی تەواو',phone:'ژمارەی مۆبایل',consent:'ڕازیم بە مەرجەکانی DEVA Rewards',activate:'چالاککردنی ئەندامێتی',congrats:'🎉 پیرۆزە!',giftHelp:'سندوقەکە بکەرەوە بۆ بینینی خەڵاتەکەت.'},
ar:{nav:'هدايا DEVA',launchTitle:'هدايا DEVA',launchText:'امسح رمز QR مرة واحدة في المعرض وشارك باستمرار في السحب الأسبوعي. بعد الوصول إلى 1,000 عضو، تُقدَّم الجوائز كل يوم جمعة الساعة 9 مساءً.',view:'عرض الهدايا',mainTitle:'جوائز DEVA الأسبوعية',mainText:'نزّل التطبيق وامسح رمز QR مرة واحدة فقط في المعرض لتصبح عضواً دائماً. بعد الوصول إلى 1,000 عضو، يُجرى السحب كل جمعة الساعة 9 مساءً.',drawLabel:'موعد السحب',drawText:'كل جمعة • 9:00 مساءً',prizes:'🎁 الجوائز',scan:'امسح QR',join:'تحقق من عضويتي',notify:'تفعيل الإشعارات',credit:'رصيد DEVA ليس نقداً ويُستخدم فقط للمشتريات القادمة. تحدد DEVA الشروط والحد الأدنى للشراء.',winners:'🏆 قائمة الفائزين',float:'الهدايا',activateTitle:'تفعيل DEVA Rewards',activateHelp:'امسح رمز QR في المعرض. تحتاج إلى ذلك مرة واحدة فقط.',name:'الاسم الكامل',phone:'رقم الهاتف',consent:'أوافق على شروط DEVA Rewards',activate:'تفعيل العضوية',congrats:'🎉 مبروك!',giftHelp:'افتح الصندوق لرؤية جائزتك.'},
en:{nav:'DEVA Gifts',launchTitle:'DEVA Gifts',launchText:'Scan the showroom QR once and stay entered in the weekly draw. After reaching 1,000 members, prizes are drawn every Friday at 9:00 PM.',view:'View gifts',mainTitle:'DEVA Weekly Rewards',mainText:'Download the app and scan the showroom QR once to become a permanent member. After reaching 1,000 members, the draw takes place every Friday at 9:00 PM.',drawLabel:'Draw time',drawText:'Every Friday • 9:00 PM',prizes:'🎁 Prizes',scan:'Scan QR',join:'Check my membership',notify:'Enable notifications',credit:'DEVA Credit is not cash and can only be used for future purchases. Terms and minimum purchase are set by DEVA.',winners:'🏆 Hall of Winners',float:'Gifts',activateTitle:'Activate DEVA Rewards',activateHelp:'Scan the QR in the showroom. You only need to do this once.',name:'Full name',phone:'Mobile number',consent:'I agree to the DEVA Rewards terms',activate:'Activate membership',congrats:'🎉 Congratulations!',giftHelp:'Open the box to reveal your prize.'},
tr:{nav:'DEVA Hediyeleri',launchTitle:'DEVA Hediyeleri',launchText:'Mağazadaki QR kodunu bir kez tarayın ve haftalık çekilişe sürekli katılın. 1.000 üyeye ulaşıldıktan sonra her Cuma saat 21:00’de ödüller verilir.',view:'Hediyeleri gör',mainTitle:'DEVA Haftalık Ödülleri',mainText:'Uygulamayı indirin ve kalıcı üye olmak için mağazadaki QR kodunu yalnızca bir kez tarayın. 1.000 üyeye ulaşıldıktan sonra çekiliş her Cuma saat 21:00’de yapılır.',drawLabel:'Çekiliş zamanı',drawText:'Her Cuma • 21:00',prizes:'🎁 Ödüller',scan:'QR Tara',join:'Üyeliğimi kontrol et',notify:'Bildirimleri aç',credit:'DEVA Credit nakit değildir ve yalnızca gelecekteki alışverişlerde kullanılabilir. Koşullar ve minimum alışveriş tutarı DEVA tarafından belirlenir.',winners:'🏆 Kazananlar',float:'Hediyeler',activateTitle:'DEVA Rewards Aktivasyonu',activateHelp:'Mağazadaki QR kodunu tarayın. Bunu yalnızca bir kez yapmanız yeterlidir.',name:'Ad Soyad',phone:'Telefon numarası',consent:'DEVA Rewards koşullarını kabul ediyorum',activate:'Üyeliği etkinleştir',congrats:'🎉 Tebrikler!',giftHelp:'Ödülünüzü görmek için kutuyu açın.'}
};
const q=s=>document.querySelector(s), put=(s,v)=>{const e=q(s);if(e)e.textContent=v};
function apply(l){const x=R[l]||R.en;put('#rewardNavText',x.nav);put('#rewardLaunchTitle',x.launchTitle);put('#rewardLaunchText',x.launchText);put('#rewardLaunchBtn',x.view);put('#rewardMainTitle',x.mainTitle);put('#rewardMainText',x.mainText);put('#rewardDrawTimeLabel',x.drawLabel);put('#rewardDrawTimeText',x.drawText);put('#rewardPrizesTitle',x.prizes);put('#rewardScanBtn span',x.scan);put('#rewardJoinBtn',x.join);put('#rewardNotifyBtn span',x.notify);put('#rewardCreditNote',x.credit);put('#rewardWinnersTitle',x.winners);put('#rewardFloatText',x.float);put('#rewardActivateTitle',x.activateTitle);put('#rewardActivateHelp',x.activateHelp);const n=q('#rewardName'),p=q('#rewardPhone');if(n)n.placeholder=x.name;if(p)p.placeholder=x.phone;put('#rewardConsentText',x.consent);put('#rewardActivateBtn',x.activate);put('#rewardCongrats',x.congrats);put('#rewardGiftHelp',x.giftHelp)}
window.addEventListener('deva-language-change',e=>apply(e.detail?.lang||localStorage.getItem('deva-lang')||'ku'));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>apply(localStorage.getItem('deva-lang')||'ku'));else apply(localStorage.getItem('deva-lang')||'ku');
})();
