(()=>{const admin=document.getElementById('adminBtn');if(admin)admin.onclick=()=>location.href='admin.html';
function getCart(){try{return JSON.parse(localStorage.getItem('deva-cart')||'{}')}catch{return{}}}function getProfile(){try{return JSON.parse(localStorage.getItem('deva-profile')||'{}')}catch{return{}}}
const oldOpen=window.openDrawer;document.addEventListener('click',e=>{if(e.target?.id==='cartBtn'||e.target?.closest?.('#cartBtn'))setTimeout(addFib,120)});
function addFib(){const f=document.getElementById('drawerFooter');if(!f||document.getElementById('fibPay'))return;const b=document.createElement('button');b.id='fibPay';b.className='checkout-btn';b.textContent='پارەدان بە FIB';b.style.marginTop='10px';b.onclick=pay;f.appendChild(b)}
async function pay(){const cart=getCart(),profile=getProfile();const entries=Object.entries(cart);if(!entries.length)return alert('سەبەتەکە بەتاڵە');if(!profile.name||!profile.phone)return alert('سەرەتا ناو و ژمارەی مۆبایل لە هەژمارەکەت هەڵبگرە');const products=(window.DEVA_DATA||window.D)?.products||[];const items=entries.map(([id,qty])=>{const p=products.find(x=>String(x.id)===String(id));const priceUsd=Number(String(p?.price||0).replace(/[^0-9.]/g,''));return{id,name:p?.name||id,qty:Number(qty),priceUsd}});if(items.some(x=>!x.priceUsd))return alert('هەندێک بەرهەم نرخەکەی دیاری نەکراوە');try{const r=await fetch('/api/orders/fib',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customer:{name:profile.name,phone:profile.phone,email:profile.email||''},items})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Payment failed');showFib(d)}catch(e){alert(e.message)}}
function showFib(d){const w=window.open('','_blank','noopener,noreferrer');if(w&&d.personalAppLink){w.location=d.personalAppLink;return}const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="modal-box single-modal"><button aria-label="close">×</button><div class="panel-content"><h2>FIB Payment</h2><p>Order: <b>${d.orderId}</b></p><p>${Number(d.amountIqd).toLocaleString()} IQD</p>${d.qrCode?`<img src="${d.qrCode}" alt="FIB QR" style="max-width:260px;width:100%">`:''}<p>Code: <b>${d.readableCode||''}</b></p><a class="gold-btn" target="_blank" rel="noopener" href="${d.personalAppLink||'#'}">Open FIB</a></div></div>`;m.querySelector('button').onclick=()=>m.remove();document.body.appendChild(m)}
})();


// Monthly customer gift campaign
(()=>{let activeGift=null,timer=null;const q=s=>document.querySelector(s);async function loadGift(){try{const r=await fetch('/api/monthly-gift',{credentials:'same-origin'});if(!r.ok)return;activeGift=await r.json();if(!activeGift)return;const sec=q('#monthlyGiftSection');if(!sec)return;sec.hidden=false;q('#monthlyGiftTitle').textContent=activeGift.title;q('#monthlyGiftName').textContent=activeGift.gift_name;q('#monthlyGiftDescription').textContent=activeGift.description||'';q('#monthlyGiftTerms').textContent=activeGift.terms||(window.DEVA_MONTHLY_GIFT_I18N?.t?.().defaultTerms||'');if(activeGift.image){const im=q('#monthlyGiftImage');im.src=activeGift.image;im.hidden=false}tick();timer=setInterval(tick,1000)}catch{}}function tick(){if(!activeGift)return;const ms=new Date(activeGift.end_at)-Date.now(),el=q('#monthlyGiftCountdown');if(ms<=0){el.textContent=window.DEVA_MONTHLY_GIFT_I18N?.t?.().ended||'Campaign ended';clearInterval(timer);return}const d=Math.floor(ms/86400000),h=Math.floor(ms/3600000)%24,m=Math.floor(ms/60000)%60,ss=Math.floor(ms/1000)%60;{const x=window.DEVA_MONTHLY_GIFT_I18N?.t?.()||{};el.innerHTML=`<b>${d} ${x.day||''}</b><b>${h} ${x.hour||''}</b><b>${m} ${x.minute||''}</b><b>${ss} ${x.second||''}</b>`}}q('#monthlyGiftForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=q('#monthlyGiftMessage');if(!activeGift)return;msg.textContent=window.DEVA_MONTHLY_GIFT_I18N?.t?.().sending||'Sending...';try{const r=await fetch('/api/monthly-gift/'+activeGift.id+'/enter',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customer_name:q('#giftCustomerName').value,phone:q('#giftCustomerPhone').value,email:q('#giftCustomerEmail').value,city:q('#giftCustomerCity').value,website:q('#giftWebsite').value,consent:q('#giftConsent').checked})});const d=await r.json();if(!r.ok)throw new Error(d.error||'هەڵەیەک ڕوویدا');msg.textContent=d.message;e.target.reset()}catch(x){msg.textContent=x.message}});loadGift()})();


// DEVA Monthly Gift — 4-language UI localization
(()=>{
 const T={
  ku:{join:'بەژداری بکە',name:'ناوی تەواو',phone:'ژمارەی مۆبایل',email:'ئیمەیڵ (ئارەزوومەندانە)',city:'شار',consent:'ڕازیم بە مەرجەکانی بەژداربوون',submit:'بەژداری کردن',terms:'مەرجەکان',defaultTerms:'هەر کریارێک تەنها یەک جار دەتوانێت بەژدار بێت.',ended:'کەمپەینەکە کۆتایی هات',sending:'ناردن...',day:'ڕۆژ',hour:'کاتژمێر',minute:'خولەک',second:'چرکە'},
  ar:{join:'شارك الآن',name:'الاسم الكامل',phone:'رقم الهاتف',email:'البريد الإلكتروني (اختياري)',city:'المدينة',consent:'أوافق على شروط المشاركة',submit:'إرسال المشاركة',terms:'الشروط',defaultTerms:'يمكن لكل عميل المشاركة مرة واحدة فقط.',ended:'انتهت الحملة',sending:'جارٍ الإرسال...',day:'يوم',hour:'ساعة',minute:'دقيقة',second:'ثانية'},
  en:{join:'Join now',name:'Full name',phone:'Mobile number',email:'Email (optional)',city:'City',consent:'I agree to the participation terms',submit:'Enter the draw',terms:'Terms',defaultTerms:'Each customer may enter only once.',ended:'Campaign ended',sending:'Sending...',day:'day',hour:'hour',minute:'minute',second:'second'},
  tr:{join:'Katıl',name:'Ad Soyad',phone:'Telefon numarası',email:'E-posta (isteğe bağlı)',city:'Şehir',consent:'Katılım koşullarını kabul ediyorum',submit:'Çekilişe katıl',terms:'Koşullar',defaultTerms:'Her müşteri yalnızca bir kez katılabilir.',ended:'Kampanya sona erdi',sending:'Gönderiliyor...',day:'gün',hour:'saat',minute:'dakika',second:'saniye'}
 };
 const q=s=>document.querySelector(s),lang=()=>localStorage.getItem('deva-lang')||'ku',t=()=>T[lang()]||T.ku;
 function apply(){const x=t(),f=q('#monthlyGiftForm');if(!f)return;const h=f.querySelector('h3');if(h)h.textContent=x.join;[['#giftCustomerName','name'],['#giftCustomerPhone','phone'],['#giftCustomerEmail','email'],['#giftCustomerCity','city']].forEach(([s,k])=>{const e=q(s);if(e)e.placeholder=x[k]});const lab=f.querySelector('.gift-consent');if(lab){const inp=lab.querySelector('input');lab.childNodes.forEach(n=>{if(n.nodeType===3)n.remove()});lab.append(document.createTextNode(' '+x.consent));if(inp&&!lab.contains(inp))lab.prepend(inp)}const b=f.querySelector('button[type="submit"]');if(b)b.textContent=x.submit;const sum=f.querySelector('details summary');if(sum)sum.textContent=x.terms;}
 window.DEVA_MONTHLY_GIFT_I18N={t,apply};window.addEventListener('deva-language-change',apply);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();
})();
