import 'dotenv/config';import express from 'express';import helmet from 'helmet';import cors from 'cors';import bcrypt from 'bcryptjs';import crypto from 'node:crypto';import {z} from 'zod';import {db,syncBuiltinCatalog} from './db.js';import {authLimiter,apiLimiter,sensitiveLimiter,requireAdmin,requireCsrf,allowRoles,allowPermission,signAdmin,setSessionCookie,clearSessionCookie,revokeCurrentToken,audit,passwordIsStrong,pruneSecurityTables,securityAlert} from './security.js';import {createFibPayment,getFibStatus} from './fib.js';import {newTotpSecret,verifyTotp,otpauthUri} from './totp.js';import fs from 'node:fs';import multer from 'multer';import QRCode from 'qrcode';import path from 'node:path';import {fileURLToPath} from 'node:url';import {signCustomer,requireCustomer,optionalCustomer} from './customer-auth.js';
import {sendExpoPush} from './push.js';
if(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<64)throw new Error('JWT_SECRET must be at least 64 random characters');
if(process.env.NODE_ENV==='production'&&process.env.PUBLIC_BASE_URL?.startsWith('http://'))throw new Error('Production requires HTTPS PUBLIC_BASE_URL');
if(process.env.FIB_MODE==='production'&&String(process.env.FIB_BASE_URL||'').includes('.stage.'))throw new Error('FIB production mode cannot use the stage/sandbox base URL');
const app=express();app.disable('x-powered-by');app.get('/favicon.ico',(_req,res)=>res.status(204).end());if(process.env.TRUST_PROXY==='true')app.set('trust proxy',1);pruneSecurityTables();setInterval(pruneSecurityTables,6*60*60*1000).unref();
app.use((req,res,next)=>{req.id=crypto.randomUUID();res.setHeader('X-Request-ID',req.id);next()});
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],imgSrc:["'self'",'data:','blob:','https:'],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],connectSrc:["'self'"],fontSrc:["'self'",'data:'],objectSrc:["'none'"],frameAncestors:["'none'"]}}}));
app.use(cors({origin:(o,cb)=>{const allowed=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);const ok=!o||allowed.includes(o);cb(ok?null:new Error('CORS blocked'),ok)},credentials:true,methods:['GET','POST','PATCH','DELETE'],allowedHeaders:['Content-Type','X-CSRF-Token','Authorization']}));app.use(express.json({limit:'100kb',strict:true}));app.use('/api',(req,res,next)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Pragma','no-cache');res.setHeader('X-DEVA-Build','D35');next()});app.use('/api',(req,res,next)=>{if(String(req.path||'').startsWith('/admin/'))return next();return apiLimiter(req,res,next)});
app.get('/api/build-version',(_req,res)=>res.json({build:'D35',adminRateLimitBypass:true,adminAutoPolling:false,productMutations:'auth-csrf-fixed',oldPrice:'verified'}));
const adminEmail=(process.env.ADMIN_EMAIL||'admin@devafurniture.com').trim().toLowerCase();const adminPassword=process.env.ADMIN_PASSWORD||'';const resetAdminOnceToken=(process.env.RESET_ADMIN_ONCE_TOKEN||'').trim();let existing=db.prepare('SELECT id FROM admins WHERE email=?').get(adminEmail);if(resetAdminOnceToken){if(!passwordIsStrong(adminPassword))throw new Error('ADMIN_PASSWORD must be 14+ chars with uppercase, lowercase, number and symbol');const resetHash=crypto.createHash('sha256').update(resetAdminOnceToken).digest('hex');const alreadyReset=db.prepare('SELECT token_hash FROM admin_reset_events WHERE token_hash=?').get(resetHash);if(!alreadyReset){const tx=db.transaction(()=>{let target=existing;if(!target)target=db.prepare("SELECT id FROM admins WHERE role='SUPER_ADMIN' ORDER BY id LIMIT 1").get();const passwordHash=bcrypt.hashSync(adminPassword,14);if(target){db.prepare("UPDATE admins SET email=?,password_hash=?,role='SUPER_ADMIN',active=1,failed_attempts=0,lock_until=NULL,totp_secret=NULL,totp_enabled=0,token_version=token_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(adminEmail,passwordHash,target.id);}else{db.prepare("INSERT INTO admins(email,password_hash,role,active,failed_attempts,lock_until,totp_secret,totp_enabled) VALUES(?,?,'SUPER_ADMIN',1,0,NULL,NULL,0)").run(adminEmail,passwordHash);}db.prepare('INSERT INTO admin_reset_events(token_hash) VALUES(?)').run(resetHash);});tx();existing=db.prepare('SELECT id FROM admins WHERE email=?').get(adminEmail);console.log('DEVA Admin one-time reset applied');console.log('Admin email: '+adminEmail);console.log('2FA: OFF - re-enable after login');}}if(!existing){if(!passwordIsStrong(adminPassword))throw new Error('ADMIN_PASSWORD must be 14+ chars with uppercase, lowercase, number and symbol');db.prepare("INSERT INTO admins(email,password_hash,role) VALUES(?,?, 'SUPER_ADMIN')").run(adminEmail,bcrypt.hashSync(adminPassword,14));}
// One-time reset is handled above through RESET_ADMIN_ONCE_TOKEN and admin_reset_events.
const roles=['SUPER_ADMIN','ADMIN','STAFF'];
const publicRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../');const persistentRoot=process.env.DATA_DIR||path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../data');const backupDir=process.env.BACKUP_DIR||path.join(persistentRoot,'backups');const productUploadDir=process.env.UPLOAD_DIR||path.join(persistentRoot,'uploads','products');fs.mkdirSync(productUploadDir,{recursive:true});fs.mkdirSync(backupDir,{recursive:true});const productUpload=multer({storage:multer.diskStorage({destination:(_r,_f,cb)=>cb(null,productUploadDir),filename:(_r,f,cb)=>{const ext=({ 'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp'})[f.mimetype]||'.img';cb(null,Date.now()+'-'+crypto.randomBytes(8).toString('hex')+ext)}}),limits:{fileSize:8*1024*1024,files:1},fileFilter:(_r,f,cb)=>['image/jpeg','image/png','image/webp'].includes(f.mimetype)?cb(null,true):cb(new Error('Only JPG, PNG and WEBP images are allowed'))});
let backupRunning=false;
async function createDatabaseBackup(kind='AUTO',createdBy=null){
  if(backupRunning)return null;backupRunning=true;
  try{
    fs.mkdirSync(backupDir,{recursive:true});
    const name=`deva-${kind.toLowerCase()}-${new Date().toISOString().replace(/[:.]/g,'-')}.sqlite`;
    const dest=path.join(backupDir,name);
    await db.backup(dest);
    db.prepare('INSERT INTO backups(file_name,created_by,kind) VALUES(?,?,?)').run(name,createdBy,kind);
    return name;
  }finally{backupRunning=false}
}
function pruneBackups(){
  const days=Math.max(1,Number(process.env.BACKUP_RETENTION_DAYS||30));
  const cutoff=Date.now()-days*86400000;
  if(!fs.existsSync(backupDir))return;
  for(const f of fs.readdirSync(backupDir)){
    if(!f.endsWith('.sqlite'))continue;const full=path.join(backupDir,f);
    try{if(fs.statSync(full).mtimeMs<cutoff)fs.unlinkSync(full)}catch{}
  }
  db.prepare("DELETE FROM backups WHERE created_at < datetime('now', ?)").run(`-${days} days`);
}
function startAutomaticBackups(){
  const hours=Math.max(1,Number(process.env.BACKUP_INTERVAL_HOURS||24));
  const run=async()=>{try{const name=await createDatabaseBackup('AUTO',null);if(name)console.log(`[backup] ${name}`);pruneBackups()}catch(e){console.error('[backup] failed',e.message)}};
  setTimeout(run,60_000).unref();setInterval(run,hours*60*60*1000).unref();
}
startAutomaticBackups();
app.post('/api/admin/login',authLimiter,(req,res)=>{const s=z.object({email:z.string().email().max(254),password:z.string().min(8).max(128),code:z.string().regex(/^\d{6}$/).optional()}).strict().safeParse(req.body);if(!s.success)return res.status(400).json({error:'Invalid input'});const email=s.data.email.toLowerCase();const a=db.prepare('SELECT * FROM admins WHERE email=?').get(email);const now=Math.floor(Date.now()/1000);if(a?.lock_until&&a.lock_until>now){audit(req,'LOGIN_BLOCKED',email,{lockUntil:a.lock_until});securityAlert(req,'ACCOUNT_LOCKED',`Account locked: ${email}`,'HIGH',a.id);return res.status(423).json({error:'Account temporarily locked'});}if(!a||!a.active||!bcrypt.compareSync(s.data.password,a.password_hash)){if(a){const attempts=(a.failed_attempts||0)+1;const lock=attempts>=5?now+15*60:null;db.prepare('UPDATE admins SET failed_attempts=?,lock_until=? WHERE id=?').run(lock?0:attempts,lock,a.id);if(lock)securityAlert(req,'BRUTE_FORCE',`Multiple failed login attempts: ${email}`,'HIGH',a.id);}audit(req,'LOGIN_FAILED',email);return res.status(401).json({error:'Invalid credentials'});}if(a.totp_enabled){if(!s.data.code)return res.status(202).json({requires2fa:true});if(!verifyTotp(a.totp_secret,s.data.code)){audit(req,'TWO_FACTOR_FAILED',email);securityAlert(req,'TWO_FACTOR_FAILED',`Invalid 2FA code: ${email}`,'HIGH',a.id);return res.status(401).json({error:'Invalid authentication code'});}}db.prepare('UPDATE admins SET failed_attempts=0,lock_until=NULL,last_login_at=CURRENT_TIMESTAMP WHERE id=?').run(a.id);req.admin={sub:a.id,email:a.email,role:a.role};audit(req,'LOGIN');const session=signAdmin(a);setSessionCookie(res,session.token);res.json({csrfToken:session.csrf,sessionToken:session.token,admin:{id:a.id,email:a.email,role:a.role}})});
app.get('/api/admin/me',requireAdmin,(req,res)=>{const a=db.prepare('SELECT totp_enabled FROM admins WHERE id=?').get(req.admin.sub);res.json({...req.admin,csrfToken:req.admin.csrf,totpEnabled:!!a.totp_enabled})});
app.post('/api/admin/2fa/setup',requireAdmin,requireCsrf,sensitiveLimiter,(req,res)=>{const secret=newTotpSecret();db.prepare('UPDATE admins SET totp_secret=?,totp_enabled=0 WHERE id=?').run(secret,req.admin.sub);audit(req,'TWO_FACTOR_SETUP_STARTED');res.json({secret,otpauthUri:otpauthUri(secret,req.admin.email)});});
app.post('/api/admin/2fa/enable',requireAdmin,requireCsrf,sensitiveLimiter,(req,res)=>{const s=z.object({code:z.string().regex(/^\d{6}$/)}).safeParse(req.body);const a=db.prepare('SELECT totp_secret FROM admins WHERE id=?').get(req.admin.sub);if(!s.success||!a?.totp_secret||!verifyTotp(a.totp_secret,s.data.code))return res.status(400).json({error:'Invalid authentication code'});db.prepare('UPDATE admins SET totp_enabled=1,token_version=token_version+1 WHERE id=?').run(req.admin.sub);audit(req,'TWO_FACTOR_ENABLED');securityAlert(req,'TWO_FACTOR_ENABLED','Two-factor authentication enabled','INFO');clearSessionCookie(res);res.json({ok:true});});
app.post('/api/admin/2fa/disable',requireAdmin,requireCsrf,sensitiveLimiter,(req,res)=>{const s=z.object({password:z.string(),code:z.string().regex(/^\d{6}$/)}).safeParse(req.body);const a=db.prepare('SELECT password_hash,totp_secret FROM admins WHERE id=?').get(req.admin.sub);if(!s.success||!bcrypt.compareSync(s.data.password,a.password_hash)||!verifyTotp(a.totp_secret,s.data.code))return res.status(401).json({error:'Verification failed'});db.prepare('UPDATE admins SET totp_enabled=0,totp_secret=NULL,token_version=token_version+1 WHERE id=?').run(req.admin.sub);audit(req,'TWO_FACTOR_DISABLED');clearSessionCookie(res);res.json({ok:true});});
app.post('/api/admin/logout-all',requireAdmin,requireCsrf,(req,res)=>{db.prepare('UPDATE admins SET token_version=token_version+1 WHERE id=?').run(req.admin.sub);audit(req,'LOGOUT_ALL_DEVICES');clearSessionCookie(res);res.json({ok:true});});
app.get('/api/admin/security-center',requireAdmin,allowPermission('security.manage'),(req,res)=>{const alerts=db.prepare('SELECT * FROM security_alerts ORDER BY id DESC LIMIT 100').all();const recent=db.prepare("SELECT actor,action,ip,user_agent,created_at FROM audit_logs WHERE action IN ('LOGIN','LOGIN_FAILED','TWO_FACTOR_FAILED','LOGIN_BLOCKED') ORDER BY id DESC LIMIT 100").all();const now=Math.floor(Date.now()/1000);const stats={failed24h:db.prepare("SELECT count(*) n FROM audit_logs WHERE action='LOGIN_FAILED' AND created_at>=datetime('now','-1 day')").get().n,alertsUnread:db.prepare('SELECT count(*) n FROM security_alerts WHERE read_at IS NULL').get().n,admins:db.prepare('SELECT count(*) n FROM admins WHERE active=1').get().n,twoFactor:db.prepare('SELECT count(*) n FROM admins WHERE active=1 AND totp_enabled=1').get().n,lockedAdmins:db.prepare('SELECT count(*) n FROM admins WHERE active=1 AND lock_until>?').get(now).n,lastLogin:db.prepare("SELECT actor,created_at FROM audit_logs WHERE action='LOGIN' ORDER BY id DESC LIMIT 1").get()||null};res.json({stats,alerts,recent});});
app.post('/api/admin/security-alerts/read',requireAdmin,requireCsrf,allowPermission('security.manage'),(req,res)=>{db.prepare('UPDATE security_alerts SET read_at=CURRENT_TIMESTAMP WHERE read_at IS NULL').run();res.json({ok:true});});
app.get('/api/admin/permissions',requireAdmin,(req,res)=>res.json(db.prepare('SELECT role,permission FROM role_permissions ORDER BY role,permission').all()));
app.post('/api/admin/backups',requireAdmin,requireCsrf,sensitiveLimiter,allowPermission('backups.manage'),async(req,res)=>{try{const name=await createDatabaseBackup('MANUAL',req.admin.sub);if(!name)return res.status(409).json({error:'Backup already running'});audit(req,'BACKUP_CREATED',name);pruneBackups();res.json({ok:true,file:name})}catch{return res.status(500).json({error:'Backup failed'})}});
app.get('/api/admin/backups',requireAdmin,allowPermission('backups.manage'),(req,res)=>res.json(db.prepare('SELECT * FROM backups ORDER BY id DESC LIMIT 50').all()));
app.get('/api/admin/system-status',requireAdmin,allowPermission('security.manage'),(req,res)=>{let dbOk=true,dbError='';try{db.prepare('SELECT 1 ok').get()}catch(e){dbOk=false;dbError=e.message}const lastBackup=db.prepare('SELECT file_name,kind,created_at FROM backups ORDER BY id DESC LIMIT 1').get()||null;const resetCount=db.prepare('SELECT count(*) n FROM admin_reset_events').get().n;const productStats=db.prepare('SELECT count(*) total,sum(CASE WHEN active=1 THEN 1 ELSE 0 END) active,sum(CASE WHEN stock_qty<=0 AND active=1 THEN 1 ELSE 0 END) outOfStock,sum(CASE WHEN stock_qty>0 AND stock_qty<=low_stock_threshold AND active=1 THEN 1 ELSE 0 END) lowStock FROM products').get();res.json({ok:true,uptimeSeconds:Math.floor(process.uptime()),database:{ok:dbOk,error:dbError},storage:{persistentRoot,backupDir,productUploadDir},lastBackup,resetEvents:resetCount,products:productStats,node:process.version,environment:process.env.NODE_ENV||'development'});});
app.get('/api/admin/backups/:file/download',requireAdmin,allowPermission('backups.manage'),(req,res)=>{const file=path.basename(String(req.params.file||''));const row=db.prepare('SELECT file_name FROM backups WHERE file_name=?').get(file);if(!row)return res.status(404).json({error:'Backup not found'});const full=path.join(backupDir,file);if(!fs.existsSync(full))return res.status(404).json({error:'Backup file missing'});audit(req,'BACKUP_DOWNLOADED',file);res.download(full,file);});

app.post('/api/analytics/events',(req,res)=>{const schema=z.object({sessionId:z.string().min(8).max(80),eventType:z.enum(['page_view','product_view','whatsapp_click','order_start']),path:z.string().max(300).default('/'),referrer:z.string().max(500).optional().default(''),productId:z.string().max(120).optional().nullable()}).strict();const v=schema.safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid analytics event'});const ip=String(req.ip||'');const salt=process.env.ANALYTICS_SALT||process.env.JWT_SECRET;const ipHash=crypto.createHash('sha256').update(`${salt}:${ip}`).digest('hex').slice(0,24);db.prepare('INSERT INTO visitor_events(session_id,event_type,path,referrer,product_id,ip_hash,user_agent) VALUES(?,?,?,?,?,?,?)').run(v.data.sessionId,v.data.eventType,v.data.path,v.data.referrer||'',v.data.productId||null,ipHash,String(req.headers['user-agent']||'').slice(0,300));res.status(204).end()});
app.get('/api/admin/analytics',requireAdmin,allowPermission('orders.read'),(req,res)=>{const days=Math.min(90,Math.max(7,Number(req.query.days)||30));const modifier=`-${days-1} days`;const visits=db.prepare("SELECT count(*) n FROM visitor_events WHERE event_type='page_view' AND created_at>=datetime('now',?)").get(modifier).n;const uniqueVisitors=db.prepare("SELECT count(DISTINCT session_id) n FROM visitor_events WHERE created_at>=datetime('now',?)").get(modifier).n;const todayVisits=db.prepare("SELECT count(*) n FROM visitor_events WHERE event_type='page_view' AND date(created_at)=date('now')").get().n;const todayVisitors=db.prepare("SELECT count(DISTINCT session_id) n FROM visitor_events WHERE date(created_at)=date('now')").get().n;const sales=db.prepare("SELECT count(*) n,COALESCE(sum(total_usd),0) usd,COALESCE(sum(total_iqd),0) iqd FROM orders WHERE created_at>=datetime('now',?) AND (payment_status='PAID' OR status IN ('PAID','DELIVERED'))").get(modifier);const pending=db.prepare("SELECT count(*) n FROM orders WHERE status='PENDING'").get().n;const daily=db.prepare(`WITH RECURSIVE dates(d) AS (SELECT date('now', ?) UNION ALL SELECT date(d,'+1 day') FROM dates WHERE d<date('now')) SELECT d date,(SELECT count(*) FROM visitor_events v WHERE v.event_type='page_view' AND date(v.created_at)=d) visits,(SELECT count(*) FROM orders o WHERE date(o.created_at)=d) orders,(SELECT COALESCE(sum(o.total_usd),0) FROM orders o WHERE date(o.created_at)=d AND (o.payment_status='PAID' OR o.status IN ('PAID','DELIVERED'))) revenue_usd FROM dates`).all(modifier);const topPages=db.prepare("SELECT path,count(*) views,count(DISTINCT session_id) visitors FROM visitor_events WHERE event_type='page_view' AND created_at>=datetime('now',?) GROUP BY path ORDER BY views DESC LIMIT 8").all(modifier);const topProducts=db.prepare("SELECT product_id,count(*) views FROM visitor_events WHERE event_type='product_view' AND product_id IS NOT NULL AND created_at>=datetime('now',?) GROUP BY product_id ORDER BY views DESC LIMIT 8").all(modifier);res.json({days,summary:{visits,uniqueVisitors,todayVisits,todayVisitors,salesCount:sales.n,revenueUsd:Number(sales.usd||0),revenueIqd:Number(sales.iqd||0),pendingOrders:pending},daily,topPages,topProducts})});
app.use('/api/admin',(req,res,next)=>{if(req.method==='GET'||req.path==='/login')return next();return requireAdmin(req,res,()=>requireCsrf(req,res,next));});
app.post('/api/admin/logout',(req,res)=>{revokeCurrentToken(req);audit(req,'LOGOUT');clearSessionCookie(res);res.status(204).end()});
app.post('/api/admin/change-password',sensitiveLimiter,(req,res)=>{const s=z.object({currentPassword:z.string().min(8).max(128),newPassword:z.string().min(14).max(128)}).strict().safeParse(req.body);if(!s.success||!passwordIsStrong(s.data?.newPassword))return res.status(400).json({error:'Use 14+ chars with uppercase, lowercase, number and symbol'});const a=db.prepare('SELECT password_hash FROM admins WHERE id=?').get(req.admin.sub);if(!bcrypt.compareSync(s.data.currentPassword,a.password_hash))return res.status(401).json({error:'Current password is incorrect'});db.prepare('UPDATE admins SET password_hash=?,token_version=token_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(bcrypt.hashSync(s.data.newPassword,14),req.admin.sub);audit(req,'PASSWORD_CHANGED');clearSessionCookie(res);res.json({ok:true})});
app.get('/api/admin/admins',requireAdmin,allowRoles('SUPER_ADMIN'),(req,res)=>res.json(db.prepare('SELECT id,email,role,active,created_at,updated_at FROM admins ORDER BY created_at DESC').all()));
app.post('/api/admin/admins',allowRoles('SUPER_ADMIN'),(req,res)=>{const s=z.object({email:z.string().email(),password:z.string().min(14).max(128),role:z.enum(roles)}).safeParse(req.body);if(!s.success||!passwordIsStrong(s.data?.password))return res.status(400).json({error:'Strong password required'});try{const info=db.prepare('INSERT INTO admins(email,password_hash,role) VALUES(?,?,?)').run(s.data.email.toLowerCase(),bcrypt.hashSync(s.data.password,14),s.data.role);audit(req,'ADMIN_CREATED',String(info.lastInsertRowid),{email:s.data.email,role:s.data.role});res.status(201).json({ok:true,id:info.lastInsertRowid})}catch(e){res.status(409).json({error:'Email already exists'})}});
app.patch('/api/admin/admins/:id',allowRoles('SUPER_ADMIN'),(req,res)=>{const id=Number(req.params.id);const s=z.object({email:z.string().email().optional(),role:z.enum(roles).optional(),active:z.boolean().optional(),password:z.string().min(14).max(128).optional()}).refine(x=>Object.keys(x).length>0).safeParse(req.body);if(!s.success)return res.status(400).json({error:'Invalid input'});const target=db.prepare('SELECT * FROM admins WHERE id=?').get(id);if(!target)return res.status(404).json({error:'Admin not found'});if(id===req.admin.sub&&s.data.active===false)return res.status(400).json({error:'You cannot disable your own account'});if(s.data.password&&!passwordIsStrong(s.data.password))return res.status(400).json({error:'Strong password required'});const email=(s.data.email||target.email).toLowerCase(),role=s.data.role||target.role,active=s.data.active===undefined?target.active:(s.data.active?1:0),hash=s.data.password?bcrypt.hashSync(s.data.password,14):target.password_hash;try{db.prepare('UPDATE admins SET email=?,role=?,active=?,password_hash=?,token_version=token_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(email,role,active,hash,id);audit(req,'ADMIN_UPDATED',String(id),{email,role,active});res.json({ok:true})}catch{res.status(409).json({error:'Email already exists'})}});
app.delete('/api/admin/admins/:id',allowRoles('SUPER_ADMIN'),(req,res)=>{const id=Number(req.params.id);if(id===req.admin.sub)return res.status(400).json({error:'You cannot delete your own account'});const t=db.prepare('SELECT email FROM admins WHERE id=?').get(id);if(!t)return res.status(404).json({error:'Admin not found'});db.prepare('DELETE FROM admins WHERE id=?').run(id);audit(req,'ADMIN_DELETED',String(id),{email:t.email});res.status(204).end()});
app.get('/api/admin/audit-logs',requireAdmin,allowRoles('SUPER_ADMIN'),(req,res)=>res.json(db.prepare('SELECT id,actor,action,target,details,ip,created_at FROM audit_logs ORDER BY id DESC LIMIT 500').all()));

const giftSchema=z.object({title:z.string().min(2).max(120),description:z.string().max(1000).optional().default(''),gift_name:z.string().min(2).max(160),image:z.string().max(500).optional().default(''),terms:z.string().max(1500).optional().default(''),start_at:z.string().datetime({offset:true}),end_at:z.string().datetime({offset:true}),status:z.enum(['DRAFT','ACTIVE','CLOSED']).optional().default('DRAFT')}).refine(x=>new Date(x.end_at)>new Date(x.start_at),{message:'End date must be after start date'});
app.get('/api/monthly-gift',(req,res)=>{const g=db.prepare("SELECT id,title,description,gift_name,image,terms,start_at,end_at,status,(SELECT count(*) FROM monthly_gift_entries e WHERE e.gift_id=monthly_gifts.id) entries FROM monthly_gifts WHERE status='ACTIVE' AND datetime(start_at)<=datetime('now') AND datetime(end_at)>=datetime('now') ORDER BY start_at DESC LIMIT 1").get();res.json(g||null)});
app.post('/api/monthly-gift/:id/enter',authLimiter,(req,res)=>{const id=Number(req.params.id);const parsed=z.object({customer_name:z.string().trim().min(2).max(100),phone:z.string().trim().regex(/^[+0-9 ()-]{7,25}$/),email:z.string().email().optional().or(z.literal('')),city:z.string().trim().max(80).optional().default(''),website:z.string().max(0).optional().default(''),consent:z.literal(true)}).strict().safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'زانیارییەکان دروست بنووسە'});const g=db.prepare("SELECT id FROM monthly_gifts WHERE id=? AND status='ACTIVE' AND datetime(start_at)<=datetime('now') AND datetime(end_at)>=datetime('now')").get(id);if(!g)return res.status(404).json({error:'ئەم دیارییە چالاک نییە'});const phone=parsed.data.phone.replace(/[^+0-9]/g,'');try{const info=db.prepare('INSERT INTO monthly_gift_entries(gift_id,customer_name,phone,email,city,ip,user_agent) VALUES(?,?,?,?,?,?,?)').run(id,parsed.data.customer_name,phone,parsed.data.email||null,parsed.data.city||null,req.ip,String(req.headers['user-agent']||'').slice(0,500));res.status(201).json({ok:true,entryId:info.lastInsertRowid,message:'بە سەرکەوتوویی بەژدارت بوویت'})}catch(e){if(String(e.message).includes('UNIQUE'))return res.status(409).json({error:'بەم ژمارەیە پێشتر بەژدارت بوویت'});throw e}});
app.get('/api/admin/monthly-gifts',requireAdmin,allowPermission('gifts.manage'),(req,res)=>res.json(db.prepare("SELECT g.*,(SELECT count(*) FROM monthly_gift_entries e WHERE e.gift_id=g.id) entries,(SELECT customer_name FROM monthly_gift_entries e WHERE e.id=g.winner_entry_id) winner_name FROM monthly_gifts g ORDER BY g.id DESC").all()));
app.post('/api/admin/monthly-gifts',allowPermission('gifts.manage'),(req,res)=>{const v=giftSchema.safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid gift data'});if(v.data.status==='ACTIVE')db.prepare("UPDATE monthly_gifts SET status='CLOSED',updated_at=CURRENT_TIMESTAMP WHERE status='ACTIVE'").run();const x=v.data;const info=db.prepare('INSERT INTO monthly_gifts(title,description,gift_name,image,terms,start_at,end_at,status,created_by) VALUES(?,?,?,?,?,?,?,?,?)').run(x.title,x.description,x.gift_name,x.image,x.terms,x.start_at,x.end_at,x.status,req.admin.sub);audit(req,'MONTHLY_GIFT_CREATED',String(info.lastInsertRowid),{title:x.title,status:x.status});res.status(201).json({ok:true,id:info.lastInsertRowid})});
app.patch('/api/admin/monthly-gifts/:id',allowPermission('gifts.manage'),(req,res)=>{const id=Number(req.params.id);const old=db.prepare('SELECT * FROM monthly_gifts WHERE id=?').get(id);if(!old)return res.status(404).json({error:'Gift not found'});const v=giftSchema.partial().refine(x=>!x.start_at||!x.end_at||new Date(x.end_at)>new Date(x.start_at)).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid gift data'});const x={...old,...v.data};if(x.status==='ACTIVE')db.prepare("UPDATE monthly_gifts SET status='CLOSED',updated_at=CURRENT_TIMESTAMP WHERE status='ACTIVE' AND id<>?").run(id);db.prepare('UPDATE monthly_gifts SET title=?,description=?,gift_name=?,image=?,terms=?,start_at=?,end_at=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(x.title,x.description,x.gift_name,x.image,x.terms,x.start_at,x.end_at,x.status,id);audit(req,'MONTHLY_GIFT_UPDATED',String(id),{status:x.status});res.json({ok:true})});
app.get('/api/admin/monthly-gifts/:id/entries',requireAdmin,allowPermission('gifts.manage'),(req,res)=>res.json(db.prepare('SELECT id,customer_name,phone,email,city,created_at FROM monthly_gift_entries WHERE gift_id=? ORDER BY id DESC LIMIT 5000').all(Number(req.params.id))));
app.post('/api/admin/monthly-gifts/:id/draw',sensitiveLimiter,allowPermission('gifts.manage'),(req,res)=>{const id=Number(req.params.id);const g=db.prepare('SELECT * FROM monthly_gifts WHERE id=?').get(id);if(!g)return res.status(404).json({error:'Gift not found'});if(g.winner_entry_id)return res.status(409).json({error:'Winner already selected'});const ids=db.prepare('SELECT id FROM monthly_gift_entries WHERE gift_id=? ORDER BY id').all(id);if(!ids.length)return res.status(400).json({error:'No participants'});const winnerId=ids[crypto.randomInt(ids.length)].id;db.prepare("UPDATE monthly_gifts SET winner_entry_id=?,status='CLOSED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(winnerId,id);const winner=db.prepare('SELECT id,customer_name,phone,email,city,created_at FROM monthly_gift_entries WHERE id=?').get(winnerId);audit(req,'MONTHLY_GIFT_WINNER_DRAWN',String(id),{winnerEntryId:winnerId});res.json({ok:true,winner})});
app.delete('/api/admin/monthly-gifts/:id',allowPermission('gifts.manage'),(req,res)=>{const id=Number(req.params.id);db.prepare("DELETE FROM monthly_gifts WHERE id=? AND status='DRAFT'").run(id);audit(req,'MONTHLY_GIFT_DELETED',String(id));res.status(204).end()});


// ---- DEVA Rewards Club / Friday Gifts ----
const rewardsPhone=v=>String(v||'').replace(/[^0-9+]/g,'').replace(/^00964/,'+964').replace(/^964/,'+964');
const rewardToken=()=>String(process.env.REWARDS_QR_TOKEN||'');
const safeTokenEqual=(a,b)=>{a=String(a||'');b=String(b||'');if(!a||!b||a.length!==b.length)return false;return crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b))};
function rewardConfig(){return db.prepare('SELECT * FROM rewards_settings WHERE id=1').get()}
function baghdadParts(d=new Date()){const x=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Baghdad',weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));return x}
function weeklyDrawKey(d=new Date()){const x=baghdadParts(d);return `${x.year}-${x.month}-${x.day}`}
function weightedPrize(grand=false){const rows=db.prepare('SELECT * FROM rewards_prizes WHERE active=1 AND is_grand=? ORDER BY id').all(grand?1:0);if(!rows.length)return null;const total=rows.reduce((n,x)=>n+Math.max(1,Number(x.weight)||1),0);let r=crypto.randomInt(total);for(const x of rows){r-=Math.max(1,Number(x.weight)||1);if(r<0)return x}return rows[0]}
function shouldGrandDraw(){const cfg=rewardConfig();const last=db.prepare('SELECT drawn_at FROM rewards_draws WHERE is_grand=1 ORDER BY id DESC LIMIT 1').get();if(last)return Date.now()-new Date(last.drawn_at+'Z').getTime()>=90*86400000;const milestone=db.prepare('SELECT joined_at FROM rewards_members WHERE active=1 ORDER BY joined_at,id LIMIT 1 OFFSET ?').get(Math.max(0,Number(cfg.target_members||1000)-1));if(!milestone)return false;return Date.now()-new Date(milestone.joined_at+'Z').getTime()>=90*86400000}
function performRewardDraw({grand=false,key=null,actor='SYSTEM'}={}){
  const cfg=rewardConfig();const n=db.prepare('SELECT count(*) n FROM rewards_members WHERE active=1').get().n;
  if(!cfg.enabled)throw new Error('Rewards are disabled');if(n<cfg.target_members)throw new Error(`Need ${cfg.target_members-n} more members`);
  const drawKey=key||weeklyDrawKey();const exists=db.prepare('SELECT id FROM rewards_draws WHERE draw_key=? AND is_grand=?').get(drawKey,grand?1:0);if(exists)throw new Error('Draw already completed');
  const members=db.prepare('SELECT id,customer_name,phone FROM rewards_members WHERE active=1 ORDER BY id').all();const winner=members[crypto.randomInt(members.length)];const prize=weightedPrize(grand);if(!prize)throw new Error('No active prize configured');
  const code=`DEVA-${grand?'SUPER':'FRI'}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;const expiry=prize.type==='PRODUCT'?null:new Date(Date.now()+Number(cfg.credit_expiry_days||30)*86400000).toISOString();
  const proof=crypto.createHash('sha256').update(`${drawKey}|${grand?1:0}|${winner.id}|${prize.id}|${code}|${members.length}|${process.env.JWT_SECRET}`).digest('hex');
  const info=db.prepare('INSERT INTO rewards_draws(draw_key,member_id,prize_id,is_grand,participant_count,redeem_code,expires_at,proof_hash) VALUES(?,?,?,?,?,?,?,?)').run(drawKey,winner.id,prize.id,grand?1:0,members.length,code,expiry,proof);
  db.prepare('UPDATE rewards_members SET wins_count=wins_count+1,last_seen_at=CURRENT_TIMESTAMP WHERE id=?').run(winner.id);
  return {id:info.lastInsertRowid,winner,prize,redeemCode:code,proofHash:proof,participantCount:members.length,grand};
}
function maybeRunFridayRewards(){try{const cfg=rewardConfig();if(!cfg?.enabled)return;const p=baghdadParts();if(p.weekday!=='Fri'||Number(p.hour)<Number(cfg.friday_hour||21))return;const key=weeklyDrawKey();if(!db.prepare('SELECT 1 FROM rewards_draws WHERE draw_key=? AND is_grand=0').get(key)){try{performRewardDraw({grand:false,key})}catch(e){console.log('[rewards weekly]',e.message)}}if(shouldGrandDraw()&&!db.prepare('SELECT 1 FROM rewards_draws WHERE draw_key=? AND is_grand=1').get(key)){try{performRewardDraw({grand:true,key})}catch(e){console.log('[rewards grand]',e.message)}}}catch(e){console.error('[rewards scheduler]',e.message)}}
setTimeout(maybeRunFridayRewards,15_000).unref();setInterval(maybeRunFridayRewards,60_000).unref();

// Live DEVA Draw Room presence (ephemeral; no personal data stored)
const rewardPresence=new Map();
function pruneRewardPresence(){const cut=Date.now()-45000;for(const [k,v] of rewardPresence)if(v.lastSeen<cut)rewardPresence.delete(k)}
function rewardPresenceStats(){pruneRewardPresence();let rewards=0,waiting=0;for(const v of rewardPresence.values()){if(v.area==='REWARDS')rewards++;if(v.waiting)waiting++}return {onlineNow:rewardPresence.size,inRewardsNow:rewards,waitingForDraw:waiting}}
app.post('/api/rewards/presence',(req,res)=>{const v=z.object({sessionId:z.string().min(8).max(80),area:z.enum(['APP','REWARDS']).default('APP'),waiting:z.boolean().default(false)}).safeParse(req.body||{});if(!v.success)return res.status(400).json({error:'Invalid presence'});rewardPresence.set(v.data.sessionId,{...v.data,lastSeen:Date.now()});res.status(202).json({ok:true})});
app.get('/api/rewards/live',(req,res)=>res.json(rewardPresenceStats()));
app.get('/api/admin/rewards/live',requireAdmin,allowPermission('rewards.manage'),(req,res)=>res.json(rewardPresenceStats()));

app.get('/api/deploy-version',(_req,res)=>res.json({version:'D33-old-price-single-source',catalogSync:true,nextCode:true}));
app.get('/api/rewards/public',(req,res)=>{const cfg=rewardConfig();const count=db.prepare('SELECT count(*) n FROM rewards_members WHERE active=1').get().n;const prizes=db.prepare('SELECT id,label,type,value,min_purchase_usd,is_grand FROM rewards_prizes WHERE active=1 ORDER BY is_grand,id').all();const recent=db.prepare("SELECT d.id,d.drawn_at,d.is_grand,p.label,m.customer_name,m.phone FROM rewards_draws d JOIN rewards_members m ON m.id=d.member_id JOIN rewards_prizes p ON p.id=d.prize_id ORDER BY d.id DESC LIMIT 12").all().map(x=>({...x,customer_name:x.customer_name.length>2?x.customer_name.slice(0,2)+'***':'***',phone:x.phone?x.phone.slice(0,4)+'****'+x.phone.slice(-2):''}));res.json({active:!!cfg.enabled,started:count>=cfg.target_members,members:count,target:cfg.target_members,fridayHour:cfg.friday_hour,timezone:cfg.timezone,prizes,recent})});
app.get('/api/rewards/member',(req,res)=>{const phone=rewardsPhone(req.query.phone);if(phone.length<7)return res.status(400).json({error:'Phone required'});const m=db.prepare('SELECT id,customer_name,phone,email,active,joined_at,wins_count FROM rewards_members WHERE phone=?').get(phone);if(!m)return res.json({member:null,wins:[]});const wins=db.prepare("SELECT d.id,d.draw_key,d.is_grand,d.redeem_code,d.redeem_status,d.expires_at,d.drawn_at,p.label,p.type,p.value,p.min_purchase_usd FROM rewards_draws d JOIN rewards_prizes p ON p.id=d.prize_id WHERE d.member_id=? ORDER BY d.id DESC LIMIT 20").all(m.id);res.json({member:m,wins})});
app.post('/api/rewards/activate',authLimiter,(req,res)=>{const v=z.object({customer_name:z.string().trim().min(2).max(100),phone:z.string().trim().min(7).max(25),email:z.string().email().optional().or(z.literal('')),token:z.string().min(8).max(500),consent:z.literal(true)}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid member data'});const expected=rewardToken();if(expected.length<24)return res.status(503).json({error:'Rewards QR is not configured'});if(!safeTokenEqual(v.data.token,expected))return res.status(403).json({error:'Invalid DEVA showroom QR'});const phone=rewardsPhone(v.data.phone);const row=db.prepare('SELECT id FROM rewards_members WHERE phone=?').get(phone);if(row){db.prepare('UPDATE rewards_members SET customer_name=?,email=?,active=1,last_seen_at=CURRENT_TIMESTAMP WHERE id=?').run(v.data.customer_name,v.data.email||null,row.id);return res.json({ok:true,alreadyMember:true})}const info=db.prepare('INSERT INTO rewards_members(customer_name,phone,email,consent) VALUES(?,?,?,1)').run(v.data.customer_name,phone,v.data.email||null);res.status(201).json({ok:true,memberId:info.lastInsertRowid})});
app.get('/api/admin/rewards',requireAdmin,allowPermission('rewards.manage'),(req,res)=>{const cfg=rewardConfig(),count=db.prepare('SELECT count(*) n FROM rewards_members WHERE active=1').get().n;const members=db.prepare('SELECT id,customer_name,phone,email,joined_at,wins_count,active FROM rewards_members ORDER BY id DESC LIMIT 5000').all();const prizes=db.prepare('SELECT * FROM rewards_prizes ORDER BY is_grand,id').all();const draws=db.prepare("SELECT d.*,m.customer_name,m.phone,p.label prize_label,p.type prize_type,p.value prize_value FROM rewards_draws d JOIN rewards_members m ON m.id=d.member_id JOIN rewards_prizes p ON p.id=d.prize_id ORDER BY d.id DESC LIMIT 200").all();res.json({config:cfg,memberCount:count,members,prizes,draws})});
app.patch('/api/admin/rewards/settings',requireAdmin,requireCsrf,allowPermission('rewards.manage'),(req,res)=>{const v=z.object({target_members:z.number().int().min(1).max(1000000).optional(),enabled:z.boolean().optional(),friday_hour:z.number().int().min(0).max(23).optional(),credit_expiry_days:z.number().int().min(1).max(365).optional()}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid settings'});const old=rewardConfig(),x={...old,...v.data};db.prepare('UPDATE rewards_settings SET target_members=?,enabled=?,friday_hour=?,credit_expiry_days=?,updated_at=CURRENT_TIMESTAMP WHERE id=1').run(x.target_members,x.enabled?1:0,x.friday_hour,x.credit_expiry_days);audit(req,'REWARDS_SETTINGS_UPDATED','1',v.data);res.json({ok:true})});
app.patch('/api/admin/rewards/prizes/:id',requireAdmin,requireCsrf,allowPermission('rewards.manage'),(req,res)=>{const id=Number(req.params.id),old=db.prepare('SELECT * FROM rewards_prizes WHERE id=?').get(id);if(!old)return res.status(404).json({error:'Prize not found'});const v=z.object({label:z.string().min(2).max(120).optional(),value:z.number().nonnegative().optional(),min_purchase_usd:z.number().nonnegative().optional(),weight:z.number().int().min(1).max(10000).optional(),active:z.boolean().optional()}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid prize'});const x={...old,...v.data};db.prepare('UPDATE rewards_prizes SET label=?,value=?,min_purchase_usd=?,weight=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(x.label,x.value,x.min_purchase_usd,x.weight,x.active?1:0,id);audit(req,'REWARD_PRIZE_UPDATED',String(id),v.data);res.json({ok:true})});
app.post('/api/admin/rewards/draw',requireAdmin,requireCsrf,sensitiveLimiter,allowPermission('rewards.manage'),(req,res)=>{const v=z.object({grand:z.boolean().optional().default(false)}).safeParse(req.body||{});if(!v.success)return res.status(400).json({error:'Invalid draw'});try{const result=performRewardDraw({grand:v.data.grand,key:`MANUAL-${Date.now()}`,actor:req.admin.email});audit(req,'REWARD_DRAW',String(result.id),{grand:v.data.grand,winner:result.winner.id,prize:result.prize.id,proof:result.proofHash});res.json({ok:true,...result})}catch(e){res.status(409).json({error:e.message})}});
app.post('/api/admin/rewards/draws/:id/redeem',requireAdmin,requireCsrf,allowPermission('rewards.manage'),(req,res)=>{const id=Number(req.params.id);const d=db.prepare("SELECT id,redeem_status FROM rewards_draws WHERE id=?").get(id);if(!d)return res.status(404).json({error:'Draw not found'});if(d.redeem_status==='REDEEMED')return res.status(409).json({error:'Already redeemed'});db.prepare("UPDATE rewards_draws SET redeem_status='REDEEMED',redeemed_at=CURRENT_TIMESTAMP WHERE id=?").run(id);audit(req,'REWARD_REDEEMED',String(id));res.json({ok:true})});
app.get('/api/admin/rewards/qr.svg',requireAdmin,allowPermission('rewards.manage'),async(req,res)=>{const token=rewardToken();if(token.length<24)return res.status(503).send('REWARDS_QR_TOKEN not configured');const base=(process.env.PUBLIC_BASE_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');const url=`${base}/?deva_reward=${encodeURIComponent(token)}`;const svg=await QRCode.toString(url,{type:'svg',margin:2,width:420,errorCorrectionLevel:'M'});res.type('image/svg+xml').send(svg)});

const nextProductCode=()=>{const row=db.prepare("SELECT max(CAST(product_code AS INTEGER)) n FROM products WHERE product_code GLOB '[0-9]*'").get();return String(Math.max(155,Number(row?.n||155))+1).padStart(4,'0')};
const builtinCatalogById=(()=>{try{const items=JSON.parse(fs.readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)),'builtin-products.json'),'utf8'));return new Map((Array.isArray(items)?items:[]).map(x=>[String(x.id),x]));}catch(e){console.error('[D25] Failed to load bundled catalog map:',e.message);return new Map();}})();
const builtinCatalog=[...builtinCatalogById.values()];
const builtinByCode=new Map(builtinCatalog.filter(x=>x.code).map(x=>[String(x.code),x]));
const builtinByNameCategory=new Map(builtinCatalog.map(x=>[`${String(x.category||'').toLowerCase()}|${String(x.name||'').trim().toLowerCase()}`,x]));
const moneyValue=v=>{const n=Number(String(v??'').replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:0};
const builtinForRow=row=>{if(!row)return null;return builtinCatalogById.get(String(row.id))||builtinByCode.get(String(row.product_code||''))||builtinByNameCategory.get(`${String(row.category||'').toLowerCase()}|${String(row.name||'').trim().toLowerCase()}`)||null};
const canonicalProductId=id=>{const direct=builtinCatalogById.get(String(id));if(direct)return String(direct.id);const row=db.prepare('SELECT id,name,category,product_code FROM products WHERE id=?').get(String(id));const b=builtinForRow(row);return b?String(b.id):String(id)};

const productTombstoneFor=(idOrCode)=>db.prepare('SELECT product_id,product_code,deleted_at FROM product_tombstones WHERE product_id=? OR product_code=? LIMIT 1').get(String(idOrCode||''),String(idOrCode||''));
const deletedProductIds=()=>db.prepare('SELECT product_id,product_code,deleted_at FROM product_tombstones ORDER BY deleted_at DESC').all();
function purgeDeletedBuiltinRows(){
  const tombstones=deletedProductIds();
  for(const t of tombstones){
    if(t.product_id) db.prepare('DELETE FROM products WHERE id=?').run(String(t.product_id));
    if(t.product_code) db.prepare('DELETE FROM products WHERE product_code=?').run(String(t.product_code));
  }
  return tombstones.length;
}

function repairCatalogDuplicates(context='request'){
  let removed=0,created=0,repaired=0;
  const tx=db.transaction(()=>{
    for(const b of builtinCatalog){
      const code=String(b.code||'');
      if(productTombstoneFor(String(b.id))||productTombstoneFor(code)){
        db.prepare('DELETE FROM products WHERE id=? OR product_code=?').run(String(b.id),code);
        continue;
      }
      const rows=db.prepare(`SELECT * FROM products WHERE id=? OR product_code=? OR (lower(name)=lower(?) AND category=?) ORDER BY CASE WHEN id=? THEN 0 WHEN product_code=? THEN 1 ELSE 2 END, datetime(updated_at) DESC, rowid DESC`).all(String(b.id),code,String(b.name),String(b.category),String(b.id),code);
      let canonical=rows.find(r=>String(r.id)===String(b.id));
      const source=canonical||rows[0]||null;
      if(!canonical){
        db.prepare(`INSERT OR IGNORE INTO products(id,name,category,price_usd,old_price_usd,image,active,stock_qty,low_stock_threshold,product_code,images_json,catalog_origin,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).run(
          String(b.id),String(b.name),String(b.category),source?Number(source.price_usd||0):moneyValue(b.price),source?.old_price_usd??(b.oldPrice?moneyValue(b.oldPrice):null),String(b.image||''),source?Number(source.active!==0):1,Number(source?.stock_qty||0),Number(source?.low_stock_threshold??2),code,JSON.stringify(Array.isArray(b.images)?b.images:(b.image?[b.image]:[])),'BUILTIN'
        );
        canonical=db.prepare('SELECT * FROM products WHERE id=?').get(String(b.id));created++;
      }
      db.prepare(`UPDATE products SET name=?,category=?,image=?,product_code=?,images_json=?,catalog_origin='BUILTIN' WHERE id=?`).run(String(b.name),String(b.category),String(b.image||''),code,JSON.stringify(Array.isArray(b.images)?b.images:(b.image?[b.image]:[])),String(b.id));
      repaired++;
      for(const dup of rows){
        if(String(dup.id)===String(b.id))continue;
        try{db.prepare('INSERT OR IGNORE INTO customer_favorites(customer_id,product_id,created_at) SELECT customer_id,?,created_at FROM customer_favorites WHERE product_id=?').run(String(b.id),String(dup.id));db.prepare('DELETE FROM customer_favorites WHERE product_id=?').run(String(dup.id))}catch{}
        try{const carts=db.prepare('SELECT customer_id,qty FROM customer_cart WHERE product_id=?').all(String(dup.id));for(const c of carts){const ex=db.prepare('SELECT qty FROM customer_cart WHERE customer_id=? AND product_id=?').get(c.customer_id,String(b.id));if(ex)db.prepare('UPDATE customer_cart SET qty=?,updated_at=CURRENT_TIMESTAMP WHERE customer_id=? AND product_id=?').run(Math.max(Number(ex.qty||0),Number(c.qty||0)),c.customer_id,String(b.id));else db.prepare('INSERT INTO customer_cart(customer_id,product_id,qty) VALUES(?,?,?)').run(c.customer_id,String(b.id),Number(c.qty||1));}db.prepare('DELETE FROM customer_cart WHERE product_id=?').run(String(dup.id))}catch{}
        db.prepare('DELETE FROM products WHERE id=?').run(String(dup.id));removed++;
      }
    }
  });
  tx();
  if(removed||created)console.log(`[D25] Catalog identity repair (${context}): created=${created}, removedDuplicates=${removed}, repaired=${repaired}`);
  return {created,removed,repaired};
}

const repairBuiltinIdentity=(id)=>{const canonicalId=canonicalProductId(id);const builtin=builtinCatalogById.get(canonicalId);if(!builtin)return null;repairCatalogDuplicates('identity');const row=db.prepare('SELECT id,product_code FROM products WHERE id=?').get(canonicalId);return String(builtin.code||row?.product_code||'')};

// D27: guarantee that a built-in product exists before a price-only update.
// This repairs partial/corrupted SQLite states without touching image/name/category.
function ensureBuiltinProductRow(requestedId){
  const raw=String(requestedId||'');
  let builtin=builtinCatalogById.get(raw)||builtinByCode.get(raw)||null;
  if(!builtin){
    const row=db.prepare('SELECT id,name,category,product_code FROM products WHERE id=?').get(raw);
    builtin=builtinForRow(row);
  }
  if(!builtin)return raw;
  const id=String(builtin.id);
  const tombstone=productTombstoneFor(id)||productTombstoneFor(String(builtin.code||''));
  if(tombstone){const err=new Error('Product was deleted');err.code='PRODUCT_DELETED';throw err;}
  const existing=db.prepare('SELECT * FROM products WHERE id=?').get(id);
  if(!existing){
    db.prepare(`INSERT INTO products(id,name,category,price_usd,old_price_usd,image,active,stock_qty,low_stock_threshold,product_code,images_json,catalog_origin,updated_at)
      VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).run(
      id,String(builtin.name),String(builtin.category),moneyValue(builtin.price),builtin.oldPrice?moneyValue(builtin.oldPrice):null,String(builtin.image||''),1,0,2,String(builtin.code||''),JSON.stringify(Array.isArray(builtin.images)?builtin.images:(builtin.image?[builtin.image]:[])),'BUILTIN'
    );
  }else{
    // Identity fields are canonical; price fields stay exactly as previously edited.
    db.prepare(`UPDATE products SET name=?,category=?,image=?,product_code=?,images_json=?,catalog_origin='BUILTIN' WHERE id=?`).run(
      String(builtin.name),String(builtin.category),String(builtin.image||''),String(builtin.code||existing.product_code||''),JSON.stringify(Array.isArray(builtin.images)?builtin.images:(builtin.image?[builtin.image]:[])),id
    );
  }
  return id;
}

// One-time D27 recovery for older patches that accidentally left built-in products inactive.
try{
  const key='d27_builtin_active_recovery';
  if(!db.prepare('SELECT 1 FROM app_meta WHERE key=?').get(key)){
    syncBuiltinCatalog({onlyWhenEmpty:false});
    for(const b of builtinCatalog){
      if(productTombstoneFor(String(b.id))||productTombstoneFor(String(b.code||'')))continue;
      ensureBuiltinProductRow(String(b.id));
      db.prepare("UPDATE products SET active=1 WHERE id=?").run(String(b.id));
    }
    purgeDeletedBuiltinRows();
    db.prepare(`INSERT INTO app_meta(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).run(key,String(builtinCatalog.length));
    console.log(`[D27] Recovered ${builtinCatalog.length} built-in products and categories`);
  }
}catch(e){console.error('[D27] built-in active recovery failed:',e.message)}
app.get('/api/admin/products/next-code',requireAdmin,(_req,res)=>res.json({product_code:nextProductCode()}));
function ensureCatalogProducts(context='request'){
  let count=Number(db.prepare('SELECT count(*) n FROM products').get()?.n||0);
  if(count===0){
    try{
      const result=syncBuiltinCatalog({onlyWhenEmpty:true});
      count=Number(db.prepare('SELECT count(*) n FROM products').get()?.n||0);
      console.log(`[D16] Catalog self-heal (${context}): inserted=${result.inserted||0}, total=${count}, source=${result.file||'n/a'}`);
    }catch(e){
      console.error(`[D16] Catalog self-heal failed (${context}):`,e.message);
    }
  }
  purgeDeletedBuiltinRows();
  count=Number(db.prepare('SELECT count(*) n FROM products').get()?.n||0);
  return count;
}

// D33: price override layer. Discount price is stored separately from catalog identity
// so catalog repair/reseed can never erase the Admin-entered old price.
function savePriceOverride(productId, priceUsd, oldPriceUsd){
  const id=String(productId);
  const price=Number(priceUsd||0);
  const oldRaw=Number(oldPriceUsd||0);
  const old=Number.isFinite(oldRaw)&&oldRaw>0?oldRaw:null;
  db.prepare(`INSERT INTO product_price_overrides(product_id,price_usd,old_price_usd,updated_at)
    VALUES(?,?,?,CURRENT_TIMESTAMP)
    ON CONFLICT(product_id) DO UPDATE SET price_usd=excluded.price_usd,old_price_usd=excluded.old_price_usd,updated_at=CURRENT_TIMESTAMP`).run(id,price,old);
  return {price_usd:price,old_price_usd:old};
}
function productRowsWithPriceOverrides(whereSql=''){
  return db.prepare(`SELECT p.*,
    COALESCE(o.price_usd,p.price_usd) AS price_usd,
    COALESCE(o.old_price_usd,p.old_price_usd) AS old_price_usd
    FROM products p LEFT JOIN product_price_overrides o ON o.product_id=p.id
    ${whereSql}`).all();
}
app.get('/api/product-tombstones',(_req,res)=>{res.set('Cache-Control','no-store');res.json(deletedProductIds())});
app.get('/api/admin/product-tombstones',requireAdmin,(_req,res)=>{res.set('Cache-Control','no-store');res.json(deletedProductIds())});
app.get('/api/products',(req,res)=>{ensureCatalogProducts('public-products');try{repairCatalogDuplicates('public-products')}catch(e){console.error('[D25] public duplicate repair failed:',e.message)}res.set('X-DEVA-Catalog-Version','D25-single-identity');res.set('Cache-Control','no-store, no-cache, must-revalidate');res.json(productRowsWithPriceOverrides('WHERE p.active=1 ORDER BY CAST(p.product_code AS INTEGER), p.updated_at DESC'))});
app.post('/api/admin/products/upload',requireAdmin,requireCsrf,allowPermission('products.write'),productUpload.single('productImage'),(req,res)=>{const parsed=z.object({id:z.string().min(1).max(80),name:z.string().min(1).max(150),category:z.string().min(1).max(80),price_usd:z.coerce.number().nonnegative(),old_price_usd:z.coerce.number().nonnegative().optional().default(0),image:z.string().max(500).optional().default(''),active:z.enum(['true','false']).optional().default('true'),stock_qty:z.coerce.number().int().min(0).max(100000).optional().default(0),low_stock_threshold:z.coerce.number().int().min(0).max(100000).optional().default(2)}).safeParse(req.body);if(!parsed.success){if(req.file)try{fs.unlinkSync(req.file.path)}catch{}return res.status(400).json({error:'زانیاریی بەرهەمەکە تەواو بکە'});}const x=parsed.data;db.prepare('DELETE FROM product_tombstones WHERE product_id=?').run(String(x.id));const previous=db.prepare('SELECT image,product_code FROM products WHERE id=?').get(x.id);const productCode=previous?.product_code||nextProductCode();const image=req.file?`/uploads/products/${req.file.filename}`:x.image;db.prepare(`INSERT INTO products(id,name,category,price_usd,old_price_usd,image,active,stock_qty,low_stock_threshold,product_code,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET name=excluded.name,category=excluded.category,price_usd=excluded.price_usd,old_price_usd=excluded.old_price_usd,image=excluded.image,active=excluded.active,stock_qty=excluded.stock_qty,low_stock_threshold=excluded.low_stock_threshold,updated_at=CURRENT_TIMESTAMP`).run(x.id,x.name,x.category,x.price_usd,x.old_price_usd||null,image,x.active==='true'?1:0,x.stock_qty,x.low_stock_threshold,productCode);savePriceOverride(x.id,x.price_usd,x.old_price_usd);if(req.file&&previous?.image&&previous.image!==image){const oldName=String(previous.image).split('/').pop();if(oldName)try{fs.unlinkSync(path.join(productUploadDir,oldName))}catch{}}audit(req,'PRODUCT_SAVED',x.id,{name:x.name,imageUploaded:!!req.file});res.json({ok:true,id:x.id,image,product_code:productCode});});
app.get('/api/admin/products',requireAdmin,(req,res)=>{
  let total=ensureCatalogProducts('admin-products');
  purgeDeletedBuiltinRows();
  try{repairCatalogDuplicates('admin-products')}catch(e){console.error('[D25] admin duplicate repair failed:',e.message)}
  let rows=productRowsWithPriceOverrides('ORDER BY CAST(p.product_code AS INTEGER), p.updated_at DESC');
  if(rows.length===0){
    try{
      const forced=syncBuiltinCatalog({onlyWhenEmpty:false});
      rows=productRowsWithPriceOverrides('ORDER BY CAST(p.product_code AS INTEGER), p.updated_at DESC');
      total=rows.length;
      console.log(`[D18] Forced bundled catalog restore: inserted=${forced.inserted||0}, total=${total}, source=${forced.file||'n/a'}`);
    }catch(e){
      console.error('[D18] Forced bundled catalog restore failed:',e);
      return res.status(500).json({error:'Product catalog restore failed',detail:String(e?.message||e)});
    }
  }
  res.set('X-DEVA-Product-Count',String(total));
  res.set('X-DEVA-Catalog-Version','D18-bundled-155');
  res.set('Cache-Control','no-store, no-cache, must-revalidate');
  res.json(rows);
});
app.post('/api/admin/products/catalog-sync',requireAdmin,requireCsrf,allowPermission('products.write'),(req,res)=>{try{const result=syncBuiltinCatalog({onlyWhenEmpty:false});audit(req,'PRODUCT_CATALOG_SYNC','builtin',{inserted:result.inserted,total:result.total});res.json(result)}catch(e){console.error('Catalog sync failed:',e);res.status(500).json({error:'Catalog sync failed'})}});
app.post('/api/admin/products',requireAdmin,requireCsrf,allowPermission('products.write'),(req,res)=>{const s=z.object({id:z.string().min(1).max(80),name:z.string().min(1).max(150),category:z.string().min(1).max(80),price_usd:z.number().nonnegative(),old_price_usd:z.number().nonnegative().optional().default(0),image:z.string().max(500).optional().default(''),active:z.boolean().optional().default(true),stock_qty:z.number().int().min(0).max(100000).optional().default(0),low_stock_threshold:z.number().int().min(0).max(100000).optional().default(2)}).safeParse(req.body);if(!s.success)return res.status(400).json({error:s.error.flatten()});const p=s.data;const existingProduct=db.prepare('SELECT product_code FROM products WHERE id=?').get(p.id);const canonicalCode=repairBuiltinIdentity(p.id);const product_code=canonicalCode||existingProduct?.product_code||nextProductCode();db.prepare(`INSERT INTO products(id,name,category,price_usd,old_price_usd,image,active,stock_qty,low_stock_threshold,product_code,updated_at) VALUES(@id,@name,@category,@price_usd,@old_price_usd,@image,@active,@stock_qty,@low_stock_threshold,@product_code,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET name=@name,category=@category,price_usd=@price_usd,old_price_usd=@old_price_usd,image=@image,active=@active,stock_qty=@stock_qty,low_stock_threshold=@low_stock_threshold,product_code=@product_code,updated_at=CURRENT_TIMESTAMP`).run({...p,active:p.active?1:0,product_code});savePriceOverride(p.id,p.price_usd,p.old_price_usd);audit(req,'PRODUCT_SAVED',p.id,{name:p.name,product_code});res.json({ok:true,product_code})});
app.patch('/api/admin/products/:id/price',requireAdmin,requireCsrf,allowPermission('products.write'),(req,res)=>{
  const parsed=z.object({price_usd:z.coerce.number().nonnegative(),old_price_usd:z.coerce.number().nonnegative().optional().default(0)}).safeParse(req.body);
  if(!parsed.success)return res.status(400).json({error:'نرخەکە دروست بنووسە'});
  const requestedId=String(req.params.id);
  try{
    const targetId=ensureBuiltinProductRow(requestedId);
    const before=db.prepare('SELECT id,name,category,image,product_code,active FROM products WHERE id=?').get(targetId);
    if(!before)return res.status(404).json({error:'Product not found',requestedId});
    const p=parsed.data;
    const oldPrice=Number(p.old_price_usd);const storedOldPrice=Number.isFinite(oldPrice)&&oldPrice>0?oldPrice:null;const updateInfo=db.prepare('UPDATE products SET price_usd=?,old_price_usd=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(Number(p.price_usd),storedOldPrice,targetId);if(!updateInfo.changes)return res.status(404).json({error:'Product not found'});savePriceOverride(targetId,p.price_usd,p.old_price_usd);
    const after=db.prepare(`SELECT p.id,p.name,p.category,p.image,p.product_code,p.active,COALESCE(o.price_usd,p.price_usd) price_usd,COALESCE(o.old_price_usd,p.old_price_usd) old_price_usd FROM products p LEFT JOIN product_price_overrides o ON o.product_id=p.id WHERE p.id=?`).get(targetId);if(Number(after.price_usd)!==Number(p.price_usd)||Number(after.old_price_usd||0)!==Number(storedOldPrice||0))return res.status(500).json({error:'Price verification failed'});
    audit(req,'PRODUCT_PRICE_UPDATED',targetId,{requestedId,price_usd:p.price_usd,old_price_usd:p.old_price_usd,product_code:after.product_code});
    res.json({ok:true,id:targetId,product_code:after.product_code,price_usd:after.price_usd,old_price_usd:after.old_price_usd||0,identityPreserved:before.name===after.name&&before.category===after.category&&before.image===after.image&&before.product_code===after.product_code});
  }catch(e){console.error('[D29] price update failed:',e);if(e?.code==='PRODUCT_DELETED')return res.status(410).json({error:'Product was deleted — restore it before editing price'});res.status(500).json({error:'Price update failed',detail:String(e?.message||e)})}
});
// Compatibility route for older Admin builds: PATCH /api/admin/products/:id with price fields.
app.patch('/api/admin/products/:id',requireAdmin,requireCsrf,allowPermission('products.write'),(req,res,next)=>{
  if(req.body && ('price_usd' in req.body || 'old_price_usd' in req.body)){
    const parsed=z.object({price_usd:z.coerce.number().nonnegative(),old_price_usd:z.coerce.number().nonnegative().optional().default(0)}).safeParse(req.body);
    if(!parsed.success)return res.status(400).json({error:'نرخەکە دروست بنووسە'});
    const targetId=ensureBuiltinProductRow(String(req.params.id));
    const row=db.prepare('SELECT id,product_code FROM products WHERE id=?').get(targetId);
    if(!row)return res.status(404).json({error:'Product not found'});
    const compatOld=Number(parsed.data.old_price_usd)>0?Number(parsed.data.old_price_usd):null;db.prepare('UPDATE products SET price_usd=?,old_price_usd=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(Number(parsed.data.price_usd),compatOld,targetId);savePriceOverride(targetId,parsed.data.price_usd,parsed.data.old_price_usd);
    return res.json({ok:true,id:targetId,product_code:row.product_code,price_usd:Number(parsed.data.price_usd),old_price_usd:compatOld||0});
  }
  next();
});
app.patch('/api/admin/products/:id/active',requireAdmin,requireCsrf,allowPermission('products.write'),(req,res)=>{const active=!!req.body?.active;const info=db.prepare('UPDATE products SET active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(active?1:0,req.params.id);if(!info.changes)return res.status(404).json({error:'Product not found'});audit(req,active?'PRODUCT_ENABLED':'PRODUCT_DISABLED',req.params.id);res.json({ok:true,active});});
app.delete('/api/admin/products/:id',requireAdmin,requireCsrf,allowPermission('products.delete'),(req,res)=>{
  const requestedId=String(req.params.id);
  db.prepare('DELETE FROM product_price_overrides WHERE product_id=?').run(requestedId);
  const row=db.prepare('SELECT id,image,product_code,catalog_origin FROM products WHERE id=?').get(requestedId);
  const builtin=builtinCatalogById.get(requestedId)||builtinForRow(row);
  const canonicalId=String(builtin?.id||row?.id||requestedId);
  const canonicalCode=String(builtin?.code||row?.product_code||'');
  // A tombstone is required for built-in catalog items, otherwise data.js/self-heal would re-create them.
  if(builtin){
    db.prepare(`INSERT INTO product_tombstones(product_id,product_code,deleted_by,deleted_at) VALUES(?,?,?,CURRENT_TIMESTAMP)
      ON CONFLICT(product_id) DO UPDATE SET product_code=excluded.product_code,deleted_by=excluded.deleted_by,deleted_at=CURRENT_TIMESTAMP`)
      .run(canonicalId,canonicalCode||null,req.admin?.email||null);
  }
  const image=row?.image;
  db.prepare("DELETE FROM products WHERE id=? OR (?<>'' AND product_code=?)").run(canonicalId,canonicalCode,canonicalCode);
  if(image&&String(image).startsWith('/uploads/products/')){const oldName=String(image).split('/').pop();if(oldName)try{fs.unlinkSync(path.join(productUploadDir,oldName))}catch{}}
  audit(req,'PRODUCT_DELETED',canonicalId,{product_code:canonicalCode,builtin:!!builtin});
  res.status(204).end();
});
const normalizeCustomerPhone=v=>String(v||'').replace(/[^0-9+]/g,'').replace(/^00964/,'+964').replace(/^964/,'+964');

// Customer accounts for the native DEVA app and cross-device sync.
const customerRegisterSchema=z.object({name:z.string().trim().min(2).max(100),email:z.string().email().max(254),phone:z.string().trim().min(7).max(25),password:z.string().min(8).max(128)}).strict();
const customerLoginSchema=z.object({email:z.string().email().max(254),password:z.string().min(8).max(128)}).strict();
const publicCustomer=c=>({id:c.id,name:c.name,email:c.email,phone:c.phone,created_at:c.created_at,updated_at:c.updated_at});
app.post('/api/customer/register',authLimiter,(req,res)=>{const v=customerRegisterSchema.safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid customer data'});const email=v.data.email.trim().toLowerCase();const phone=normalizeCustomerPhone(v.data.phone);if(phone.length<7)return res.status(400).json({error:'Invalid phone'});if(db.prepare('SELECT 1 FROM customers WHERE email=? OR phone=?').get(email,phone))return res.status(409).json({error:'Account already exists'});const hash=bcrypt.hashSync(v.data.password,12);const info=db.prepare('INSERT INTO customers(name,email,phone,password_hash) VALUES(?,?,?,?)').run(v.data.name,email,phone,hash);const c=db.prepare('SELECT id,name,email,phone,token_version,created_at,updated_at FROM customers WHERE id=?').get(info.lastInsertRowid);res.status(201).json({token:signCustomer(c),customer:publicCustomer(c)});});
app.post('/api/customer/login',authLimiter,(req,res)=>{const v=customerLoginSchema.safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid login'});const email=v.data.email.trim().toLowerCase();const c=db.prepare('SELECT * FROM customers WHERE email=?').get(email);if(!c||!c.active||!bcrypt.compareSync(v.data.password,c.password_hash))return res.status(401).json({error:'Invalid credentials'});db.prepare('UPDATE customers SET last_login_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(c.id);const fresh=db.prepare('SELECT id,name,email,phone,token_version,created_at,updated_at FROM customers WHERE id=?').get(c.id);res.json({token:signCustomer(fresh),customer:publicCustomer(fresh)});});
app.get('/api/customer/me',requireCustomer,(req,res)=>res.json({customer:publicCustomer(req.customer)}));
app.patch('/api/customer/me',requireCustomer,(req,res)=>{const v=z.object({name:z.string().trim().min(2).max(100).optional(),phone:z.string().trim().min(7).max(25).optional()}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid profile'});const name=v.data.name??req.customer.name;const phone=v.data.phone?normalizeCustomerPhone(v.data.phone):req.customer.phone;const duplicate=db.prepare('SELECT 1 FROM customers WHERE phone=? AND id<>?').get(phone,req.customer.id);if(duplicate)return res.status(409).json({error:'Phone already used'});db.prepare('UPDATE customers SET name=?,phone=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(name,phone,req.customer.id);const c=db.prepare('SELECT id,name,email,phone,created_at,updated_at FROM customers WHERE id=?').get(req.customer.id);res.json({customer:publicCustomer(c)});});
app.post('/api/customer/logout-all',requireCustomer,(req,res)=>{db.prepare('UPDATE customers SET token_version=token_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.customer.id);res.json({ok:true});});
app.delete('/api/customer/account',requireCustomer,sensitiveLimiter,(req,res)=>{db.transaction(()=>{db.prepare('UPDATE orders SET customer_id=NULL WHERE customer_id=?').run(req.customer.id);db.prepare('DELETE FROM customers WHERE id=?').run(req.customer.id);})();res.status(204).end();});
app.get('/api/customer/favorites',requireCustomer,(req,res)=>res.json(db.prepare('SELECT p.* FROM customer_favorites f JOIN products p ON p.id=f.product_id WHERE f.customer_id=? AND p.active=1 ORDER BY f.created_at DESC').all(req.customer.id)));
app.put('/api/customer/favorites/:productId',requireCustomer,(req,res)=>{const pid=String(req.params.productId);if(!db.prepare('SELECT 1 FROM products WHERE id=? AND active=1').get(pid))return res.status(404).json({error:'Product not found'});db.prepare('INSERT OR IGNORE INTO customer_favorites(customer_id,product_id) VALUES(?,?)').run(req.customer.id,pid);res.json({ok:true});});
app.delete('/api/customer/favorites/:productId',requireCustomer,(req,res)=>{db.prepare('DELETE FROM customer_favorites WHERE customer_id=? AND product_id=?').run(req.customer.id,String(req.params.productId));res.status(204).end();});
app.get('/api/customer/cart',requireCustomer,(req,res)=>res.json(db.prepare('SELECT c.product_id,c.qty,p.name,p.category,p.price_usd,p.image,p.stock_qty FROM customer_cart c JOIN products p ON p.id=c.product_id WHERE c.customer_id=? AND p.active=1 ORDER BY c.updated_at DESC').all(req.customer.id)));
app.put('/api/customer/cart/:productId',requireCustomer,(req,res)=>{const v=z.object({qty:z.number().int().min(1).max(99)}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid quantity'});const pid=String(req.params.productId);if(!db.prepare('SELECT 1 FROM products WHERE id=? AND active=1').get(pid))return res.status(404).json({error:'Product not found'});db.prepare('INSERT INTO customer_cart(customer_id,product_id,qty) VALUES(?,?,?) ON CONFLICT(customer_id,product_id) DO UPDATE SET qty=excluded.qty,updated_at=CURRENT_TIMESTAMP').run(req.customer.id,pid,v.data.qty);res.json({ok:true});});
app.delete('/api/customer/cart/:productId',requireCustomer,(req,res)=>{db.prepare('DELETE FROM customer_cart WHERE customer_id=? AND product_id=?').run(req.customer.id,String(req.params.productId));res.status(204).end();});
app.delete('/api/customer/cart',requireCustomer,(req,res)=>{db.prepare('DELETE FROM customer_cart WHERE customer_id=?').run(req.customer.id);res.status(204).end();});
app.get('/api/customer/orders',requireCustomer,(req,res)=>res.json(db.prepare('SELECT id,total_usd,total_iqd,status,payment_status,created_at,updated_at FROM orders WHERE customer_id=? ORDER BY created_at DESC LIMIT 100').all(req.customer.id)));
app.post('/api/customer/push-token',requireCustomer,(req,res)=>{const v=z.object({platform:z.enum(['IOS','ANDROID']),token:z.string().min(16).max(4096)}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid push token'});db.prepare('INSERT INTO customer_push_tokens(customer_id,platform,token,active) VALUES(?,?,?,1) ON CONFLICT(token) DO UPDATE SET customer_id=excluded.customer_id,platform=excluded.platform,active=1,updated_at=CURRENT_TIMESTAMP').run(req.customer.id,v.data.platform,v.data.token);res.json({ok:true});});
app.delete('/api/customer/push-token',requireCustomer,(req,res)=>{const v=z.object({token:z.string().min(16).max(4096)}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid push token'});db.prepare('UPDATE customer_push_tokens SET active=0,updated_at=CURRENT_TIMESTAMP WHERE customer_id=? AND token=?').run(req.customer.id,v.data.token);res.status(204).end();});
app.post('/api/admin/push/broadcast',requireAdmin,requireCsrf,sensitiveLimiter,async(req,res)=>{const v=z.object({title:z.string().min(1).max(80),body:z.string().min(1).max(240),data:z.record(z.union([z.string(),z.number(),z.boolean()])).optional()}).strict().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid notification'});const tokens=db.prepare('SELECT token FROM customer_push_tokens WHERE active=1').all().map(x=>x.token);try{const out=await sendExpoPush(tokens,v.data);audit(req,'PUSH_BROADCAST','customers',{sent:out.sent,title:v.data.title});res.json({ok:true,sent:out.sent});}catch(e){res.status(502).json({error:e.message})}});

const orderSchema=z.object({customer:z.object({name:z.string().min(2).max(100),phone:z.string().min(7).max(25),email:z.string().email().optional().or(z.literal(''))}),items:z.array(z.object({id:z.string().max(80),name:z.string().max(150),qty:z.number().int().min(1).max(20),priceUsd:z.number().nonnegative()})).min(1).max(50),welcomeDiscount:z.boolean().optional().default(false)});

// ---- Sponsored Ads / DEVA Partners ----
const sponsorAdSchema=z.object({company_name:z.string().min(2).max(100),title:z.string().min(2).max(160),description:z.string().max(700).optional().default(''),image:z.string().max(500).optional().default(''),cta_label:z.string().max(50).optional().default('زیاتر ببینە'),cta_url:z.string().max(700).optional().default(''),whatsapp:z.string().max(40).optional().default(''),placement:z.enum(['HOME','PRODUCTS','PARTNERS']).default('HOME'),start_at:z.string().min(10).max(40),end_at:z.string().min(10).max(40),active:z.boolean().optional().default(true)}).strict().refine(x=>new Date(x.end_at)>new Date(x.start_at),{message:'End must be after start'});
function publicSponsorAd(x){return {id:x.id,company_name:x.company_name,title:x.title,description:x.description,image:x.image,cta_label:x.cta_label,cta_url:x.cta_url,whatsapp:x.whatsapp,placement:x.placement,start_at:x.start_at,end_at:x.end_at}}
app.get('/api/sponsors/active',(req,res)=>{const placement=String(req.query.placement||'HOME').toUpperCase();const allowed=['HOME','PRODUCTS','PARTNERS'];if(!allowed.includes(placement))return res.status(400).json({error:'Invalid placement'});const rows=db.prepare("SELECT * FROM sponsor_ads WHERE active=1 AND placement=? AND datetime(start_at)<=datetime('now') AND datetime(end_at)>=datetime('now') ORDER BY id DESC LIMIT 10").all(placement);res.json(rows.map(publicSponsorAd))});
app.post('/api/sponsors/:id/view',(req,res)=>{const id=Number(req.params.id);if(Number.isInteger(id)&&id>0)db.prepare("UPDATE sponsor_ads SET views=views+1 WHERE id=? AND active=1 AND datetime(start_at)<=datetime('now') AND datetime(end_at)>=datetime('now')").run(id);res.status(204).end()});
app.post('/api/sponsors/:id/click',(req,res)=>{const id=Number(req.params.id);if(Number.isInteger(id)&&id>0)db.prepare("UPDATE sponsor_ads SET clicks=clicks+1 WHERE id=? AND active=1 AND datetime(start_at)<=datetime('now') AND datetime(end_at)>=datetime('now')").run(id);res.status(204).end()});
app.get('/api/admin/sponsors',requireAdmin,allowPermission('ads.manage'),(req,res)=>res.json(db.prepare("SELECT *,CASE WHEN active=1 AND datetime(start_at)<=datetime('now') AND datetime(end_at)>=datetime('now') THEN 1 ELSE 0 END live FROM sponsor_ads ORDER BY id DESC").all()));
app.post('/api/admin/sponsors',requireAdmin,requireCsrf,allowPermission('ads.manage'),(req,res)=>{const v=sponsorAdSchema.safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid sponsor data'});const x=v.data;const info=db.prepare('INSERT INTO sponsor_ads(company_name,title,description,image,cta_label,cta_url,whatsapp,placement,start_at,end_at,active,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(x.company_name,x.title,x.description,x.image,x.cta_label,x.cta_url,x.whatsapp,x.placement,x.start_at,x.end_at,x.active?1:0,req.admin.sub);audit(req,'SPONSOR_AD_CREATED',String(info.lastInsertRowid),{company:x.company_name,placement:x.placement});res.status(201).json({ok:true,id:info.lastInsertRowid})});
app.patch('/api/admin/sponsors/:id',requireAdmin,requireCsrf,allowPermission('ads.manage'),(req,res)=>{const id=Number(req.params.id);const old=db.prepare('SELECT * FROM sponsor_ads WHERE id=?').get(id);if(!old)return res.status(404).json({error:'Sponsor ad not found'});const v=sponsorAdSchema.partial().safeParse(req.body);if(!v.success)return res.status(400).json({error:'Invalid sponsor data'});const x={...old,...v.data};if(new Date(x.end_at)<=new Date(x.start_at))return res.status(400).json({error:'End must be after start'});db.prepare('UPDATE sponsor_ads SET company_name=?,title=?,description=?,image=?,cta_label=?,cta_url=?,whatsapp=?,placement=?,start_at=?,end_at=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(x.company_name,x.title,x.description,x.image,x.cta_label,x.cta_url,x.whatsapp,x.placement,x.start_at,x.end_at,x.active?1:0,id);audit(req,'SPONSOR_AD_UPDATED',String(id),{company:x.company_name,placement:x.placement,active:!!x.active});res.json({ok:true})});
app.delete('/api/admin/sponsors/:id',requireAdmin,requireCsrf,allowPermission('ads.manage'),(req,res)=>{const id=Number(req.params.id);const row=db.prepare('SELECT company_name FROM sponsor_ads WHERE id=?').get(id);if(!row)return res.status(404).json({error:'Sponsor ad not found'});db.prepare('DELETE FROM sponsor_ads WHERE id=?').run(id);audit(req,'SPONSOR_AD_DELETED',String(id),{company:row.company_name});res.status(204).end()});
app.get('/api/welcome-discount/eligibility',(req,res)=>{const phone=normalizeCustomerPhone(req.query.phone);if(phone.length<7)return res.status(400).json({error:'Phone required'});const claim=db.prepare('SELECT status,order_id FROM welcome_discount_claims WHERE phone=?').get(phone);const previous=db.prepare("SELECT id FROM orders WHERE phone=? AND status NOT IN ('CANCELLED','PAYMENT_ERROR') LIMIT 1").get(phone);res.json({eligible:!claim&&!previous,percent:20,code:'WELCOME20'});});
app.post('/api/orders/fib',optionalCustomer,async(req,res)=>{const s=orderSchema.safeParse(req.body);if(!s.success)return res.status(400).json({error:'Invalid order'});const subtotalUsd=s.data.items.reduce((n,i)=>n+i.qty*i.priceUsd,0);if(subtotalUsd<=0)return res.status(400).json({error:'Price required'});const phone=normalizeCustomerPhone(s.data.customer.phone);const id='DEVA-'+crypto.randomInt(100000,999999);let discountUsd=0,discountCode=null;
try{db.transaction(()=>{if(s.data.welcomeDiscount){const claim=db.prepare('SELECT 1 FROM welcome_discount_claims WHERE phone=?').get(phone);const previous=db.prepare("SELECT 1 FROM orders WHERE phone=? AND status NOT IN ('CANCELLED','PAYMENT_ERROR') LIMIT 1").get(phone);if(!claim&&!previous){discountUsd=Math.round(subtotalUsd*20)/100;discountCode='WELCOME20';db.prepare("INSERT INTO welcome_discount_claims(phone,order_id,status) VALUES(?,?,'RESERVED')").run(phone,id);}}const totalUsd=Math.max(0,Math.round((subtotalUsd-discountUsd)*100)/100);const totalIqd=Math.round(totalUsd*Number(process.env.IQD_PER_USD||1310));db.prepare('INSERT INTO orders(id,customer_name,phone,email,subtotal_usd,discount_usd,discount_code,total_usd,total_iqd,items_json,customer_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,s.data.customer.name,phone,s.data.customer.email||null,subtotalUsd,discountUsd,discountCode,totalUsd,totalIqd,JSON.stringify(s.data.items),req.customer?.id||null);})();}catch(e){return res.status(409).json({error:'Could not reserve welcome discount'});}
const row=db.prepare('SELECT total_usd,total_iqd,discount_usd,discount_code FROM orders WHERE id=?').get(id);try{const p=await createFibPayment({amountIqd:row.total_iqd,orderId:id});db.prepare('UPDATE orders SET payment_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(p.paymentId,id);res.status(201).json({orderId:id,subtotalUsd,discountUsd:row.discount_usd,discountCode:row.discount_code,totalUsd:row.total_usd,amountIqd:row.total_iqd,...p})}catch(e){db.transaction(()=>{db.prepare("UPDATE orders SET status='PAYMENT_ERROR',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);if(discountCode)db.prepare("DELETE FROM welcome_discount_claims WHERE order_id=? AND status='RESERVED'").run(id);})();res.status(503).json({error:e.message,orderId:id})}});
app.get('/api/orders/:id/payment-status',async(req,res)=>{const o=db.prepare('SELECT id,payment_id,payment_status,status FROM orders WHERE id=?').get(req.params.id);if(!o)return res.status(404).json({error:'Not found'});if(!o.payment_id)return res.json(o);try{const s=await getFibStatus(o.payment_id);db.prepare('UPDATE orders SET payment_status=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(s.status,s.status==='PAID'?'PAID':o.status,o.id);res.json({orderId:o.id,...s})}catch(e){res.status(502).json({error:e.message})}});
app.post('/api/payments/fib/callback',(req,res)=>{const supplied=String(req.headers['x-fib-callback-secret']||'');const expected=String(process.env.FIB_CALLBACK_SECRET||'');if(!supplied||!expected||supplied.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected)))return res.status(401).end();const s=z.object({id:z.string(),status:z.enum(['PAID','UNPAID','DECLINED'])}).safeParse(req.body);if(!s.success)return res.status(406).end();db.transaction(()=>{db.prepare("UPDATE orders SET payment_status=?,status=CASE WHEN ?='PAID' THEN 'PAID' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE payment_id=?").run(s.data.status,s.data.status,s.data.id);if(s.data.status==='PAID'){const o=db.prepare('SELECT id FROM orders WHERE payment_id=?').get(s.data.id);if(o)db.prepare("UPDATE welcome_discount_claims SET status='REDEEMED',redeemed_at=CURRENT_TIMESTAMP WHERE order_id=?").run(o.id);}})();res.status(202).end()});
app.get('/api/admin/orders',requireAdmin,(req,res)=>res.json(db.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 500').all()));
app.patch('/api/admin/orders/:id',requireAdmin,requireCsrf,allowPermission('orders.write'),(req,res)=>{const s=z.object({status:z.enum(['PENDING','CONFIRMED','PREPARING','SHIPPED','DELIVERED','CANCELLED','PAID'])}).safeParse(req.body);if(!s.success)return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(s.data.status,req.params.id);audit(req,'ORDER_STATUS_CHANGED',req.params.id,{status:s.data.status});res.json({ok:true})});
const BUILD_ID=process.env.RENDER_GIT_COMMIT||process.env.RENDER_SERVICE_ID||String(Date.now());
app.set('etag', false);
app.use((req,res,next)=>{if(/\.(?:html|js|css|webmanifest)$/.test(req.path)||req.path==='/'||req.path==='/sw.js'){res.setHeader('Cache-Control','no-store, no-cache, max-age=0, must-revalidate, proxy-revalidate');res.setHeader('CDN-Cache-Control','no-store');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');res.setHeader('Surrogate-Control','no-store');res.setHeader('X-DEVA-Build',BUILD_ID)}next()});
app.use('/uploads/products',express.static(productUploadDir,{maxAge:process.env.NODE_ENV==='production'?'1h':0,immutable:false}));
app.get('/health',(_req,res)=>res.json({ok:true,service:'deva-store'}));
app.get('/admin.html',(_req,res)=>{res.set('Cache-Control','no-store, no-cache, must-revalidate');res.sendFile(path.join(publicRoot,'admin.html'))});
app.get('/admin.js',(_req,res)=>{res.set('Cache-Control','no-store, no-cache, must-revalidate');res.sendFile(path.join(publicRoot,'admin.js'))});
app.get('/admin.css',(_req,res)=>{res.set('Cache-Control','no-store, no-cache, must-revalidate');res.sendFile(path.join(publicRoot,'admin.css'))});
app.use(express.static(publicRoot,{extensions:['html'],maxAge:0,etag:false,lastModified:false,setHeaders:(res,filePath)=>{if(/\.(?:html|js|css|webmanifest)$/.test(filePath)||filePath.endsWith('/sw.js')){res.setHeader('Cache-Control','no-store, no-cache, max-age=0, must-revalidate, proxy-revalidate');res.setHeader('CDN-Cache-Control','no-store');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');res.setHeader('Surrogate-Control','no-store');res.setHeader('X-DEVA-Build',BUILD_ID)}}}));
app.get('/',(_req,res)=>{res.setHeader('Cache-Control','no-store, no-cache, max-age=0, must-revalidate, proxy-revalidate');res.setHeader('CDN-Cache-Control','no-store');res.setHeader('X-DEVA-Build',BUILD_ID);res.sendFile(path.join(publicRoot,'index.html'),{lastModified:false,cacheControl:false})});
app.use((err,req,res,next)=>{console.error(err.message);res.status(500).json({error:'Server error'})});
app.listen(process.env.PORT||3000,()=>console.log(`DEVA secure server on ${process.env.PORT||3000}`));
